// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package test

import "encoding/json"
import "fmt"
import yaml "gopkg.in/yaml.v3"
import "reflect"

type EnumIfOverlapping struct {
	// Age corresponds to the JSON schema field "age".
	Age *int `json:"age,omitempty,omitzero" yaml:"age,omitempty" mapstructure:"age,omitempty"`

	// Bark corresponds to the JSON schema field "bark".
	Bark *string `json:"bark,omitempty,omitzero" yaml:"bark,omitempty" mapstructure:"bark,omitempty"`

	// Species corresponds to the JSON schema field "species".
	Species EnumIfOverlappingSpecies `json:"species" yaml:"species" mapstructure:"species"`
}

type EnumIfOverlappingSpecies string

const EnumIfOverlappingSpeciesBird EnumIfOverlappingSpecies = "bird"
const EnumIfOverlappingSpeciesCat EnumIfOverlappingSpecies = "cat"
const EnumIfOverlappingSpeciesDog EnumIfOverlappingSpecies = "dog"

var enumValues_EnumIfOverlappingSpecies = []interface{}{
	"dog",
	"cat",
	"bird",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *EnumIfOverlappingSpecies) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_EnumIfOverlappingSpecies {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_EnumIfOverlappingSpecies, v)
	}
	*j = EnumIfOverlappingSpecies(v)
	return nil
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *EnumIfOverlappingSpecies) UnmarshalYAML(value *yaml.Node) error {
	var v string
	if err := value.Decode(&v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_EnumIfOverlappingSpecies {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_EnumIfOverlappingSpecies, v)
	}
	*j = EnumIfOverlappingSpecies(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *EnumIfOverlapping) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return fmt.Errorf("unmarshal raw EnumIfOverlapping: %w", err)
	}
	if _, ok := raw["species"]; raw != nil && !ok {
		return fmt.Errorf("field species in EnumIfOverlapping: required")
	}
	rawDisc, hasDisc := raw["species"]
	if hasDisc {
		discStr, isStr := rawDisc.(string)
		if !isStr {
			return fmt.Errorf("field species in EnumIfOverlapping: must be a string for discriminator dispatch")
		}
		if discStr == "dog" {
			if _, ok := raw["bark"]; !ok {
				return fmt.Errorf("field bark in EnumIfOverlapping (when species='dog'): required")
			}
		}
		if discStr == "dog" || discStr == "cat" {
			if _, ok := raw["age"]; !ok {
				return fmt.Errorf("field age in EnumIfOverlapping (when species='%s'): required", discStr)
			}
		}
	}
	type Plain EnumIfOverlapping
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return fmt.Errorf("unmarshal EnumIfOverlapping: %w", err)
	}
	*j = EnumIfOverlapping(plain)
	return nil
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *EnumIfOverlapping) UnmarshalYAML(value *yaml.Node) error {
	var raw map[string]interface{}
	if err := value.Decode(&raw); err != nil {
		return fmt.Errorf("unmarshal raw EnumIfOverlapping: %w", err)
	}
	if _, ok := raw["species"]; raw != nil && !ok {
		return fmt.Errorf("field species in EnumIfOverlapping: required")
	}
	rawDisc, hasDisc := raw["species"]
	if hasDisc {
		discStr, isStr := rawDisc.(string)
		if !isStr {
			return fmt.Errorf("field species in EnumIfOverlapping: must be a string for discriminator dispatch")
		}
		if discStr == "dog" {
			if _, ok := raw["bark"]; !ok {
				return fmt.Errorf("field bark in EnumIfOverlapping (when species='dog'): required")
			}
		}
		if discStr == "dog" || discStr == "cat" {
			if _, ok := raw["age"]; !ok {
				return fmt.Errorf("field age in EnumIfOverlapping (when species='%s'): required", discStr)
			}
		}
	}
	type Plain EnumIfOverlapping
	var plain Plain
	if err := value.Decode(&plain); err != nil {
		return fmt.Errorf("unmarshal EnumIfOverlapping: %w", err)
	}
	*j = EnumIfOverlapping(plain)
	return nil
}
