// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package test

type XGoExtraTags struct {
	// desc
	Key *string `json:"key,omitempty" yaml:"key,omitempty" mapstructure:"key,omitempty" env:'SERVER_URL'`
}
