// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package test

import "encoding/json"
import "fmt"
import yaml "gopkg.in/yaml.v3"
import "reflect"

type EnumIfMixedWithConst struct {
	// Id corresponds to the JSON schema field "id".
	Id *string `json:"id,omitempty,omitzero" yaml:"id,omitempty" mapstructure:"id,omitempty"`

	// Kind corresponds to the JSON schema field "kind".
	Kind EnumIfMixedWithConstKind `json:"kind" yaml:"kind" mapstructure:"kind"`

	// Payload corresponds to the JSON schema field "payload".
	Payload EnumIfMixedWithConstPayload `json:"payload,omitempty,omitzero" yaml:"payload,omitempty" mapstructure:"payload,omitempty"`
}

type EnumIfMixedWithConstKind string

const EnumIfMixedWithConstKindCreate EnumIfMixedWithConstKind = "create"
const EnumIfMixedWithConstKindDelete EnumIfMixedWithConstKind = "delete"
const EnumIfMixedWithConstKindPatch EnumIfMixedWithConstKind = "patch"
const EnumIfMixedWithConstKindUpdate EnumIfMixedWithConstKind = "update"

var enumValues_EnumIfMixedWithConstKind = []interface{}{
	"create",
	"delete",
	"update",
	"patch",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *EnumIfMixedWithConstKind) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_EnumIfMixedWithConstKind {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_EnumIfMixedWithConstKind, v)
	}
	*j = EnumIfMixedWithConstKind(v)
	return nil
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *EnumIfMixedWithConstKind) UnmarshalYAML(value *yaml.Node) error {
	var v string
	if err := value.Decode(&v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_EnumIfMixedWithConstKind {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_EnumIfMixedWithConstKind, v)
	}
	*j = EnumIfMixedWithConstKind(v)
	return nil
}

type EnumIfMixedWithConstPayload map[string]interface{}

// UnmarshalJSON implements json.Unmarshaler.
func (j *EnumIfMixedWithConst) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return fmt.Errorf("unmarshal raw EnumIfMixedWithConst: %w", err)
	}
	if _, ok := raw["kind"]; raw != nil && !ok {
		return fmt.Errorf("field kind in EnumIfMixedWithConst: required")
	}
	rawDisc, hasDisc := raw["kind"]
	if hasDisc {
		discStr, isStr := rawDisc.(string)
		if !isStr {
			return fmt.Errorf("field kind in EnumIfMixedWithConst: must be a string for discriminator dispatch")
		}
		if discStr == "create" {
			if _, ok := raw["payload"]; !ok {
				return fmt.Errorf("field payload in EnumIfMixedWithConst (when kind='create'): required")
			}
		}
		if discStr == "update" || discStr == "patch" {
			if _, ok := raw["id"]; !ok {
				return fmt.Errorf("field id in EnumIfMixedWithConst (when kind='%s'): required", discStr)
			}
			if _, ok := raw["payload"]; !ok {
				return fmt.Errorf("field payload in EnumIfMixedWithConst (when kind='%s'): required", discStr)
			}
		}
	}
	type Plain EnumIfMixedWithConst
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return fmt.Errorf("unmarshal EnumIfMixedWithConst: %w", err)
	}
	*j = EnumIfMixedWithConst(plain)
	return nil
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *EnumIfMixedWithConst) UnmarshalYAML(value *yaml.Node) error {
	var raw map[string]interface{}
	if err := value.Decode(&raw); err != nil {
		return fmt.Errorf("unmarshal raw EnumIfMixedWithConst: %w", err)
	}
	if _, ok := raw["kind"]; raw != nil && !ok {
		return fmt.Errorf("field kind in EnumIfMixedWithConst: required")
	}
	rawDisc, hasDisc := raw["kind"]
	if hasDisc {
		discStr, isStr := rawDisc.(string)
		if !isStr {
			return fmt.Errorf("field kind in EnumIfMixedWithConst: must be a string for discriminator dispatch")
		}
		if discStr == "create" {
			if _, ok := raw["payload"]; !ok {
				return fmt.Errorf("field payload in EnumIfMixedWithConst (when kind='create'): required")
			}
		}
		if discStr == "update" || discStr == "patch" {
			if _, ok := raw["id"]; !ok {
				return fmt.Errorf("field id in EnumIfMixedWithConst (when kind='%s'): required", discStr)
			}
			if _, ok := raw["payload"]; !ok {
				return fmt.Errorf("field payload in EnumIfMixedWithConst (when kind='%s'): required", discStr)
			}
		}
	}
	type Plain EnumIfMixedWithConst
	var plain Plain
	if err := value.Decode(&plain); err != nil {
		return fmt.Errorf("unmarshal EnumIfMixedWithConst: %w", err)
	}
	*j = EnumIfMixedWithConst(plain)
	return nil
}
