// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package test

import "encoding/json"
import "fmt"
import yaml "gopkg.in/yaml.v3"

type Inner struct {
	// Value corresponds to the JSON schema field "value".
	Value string `json:"value" yaml:"value" mapstructure:"value"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Inner) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return fmt.Errorf("unmarshal raw Inner: %w", err)
	}
	if _, ok := raw["value"]; raw != nil && !ok {
		return fmt.Errorf("field value in Inner: required")
	}
	type Plain Inner
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return fmt.Errorf("unmarshal Inner: %w", err)
	}
	*j = Inner(plain)
	return nil
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *Inner) UnmarshalYAML(value *yaml.Node) error {
	var raw map[string]interface{}
	if err := value.Decode(&raw); err != nil {
		return fmt.Errorf("unmarshal raw Inner: %w", err)
	}
	if _, ok := raw["value"]; raw != nil && !ok {
		return fmt.Errorf("field value in Inner: required")
	}
	type Plain Inner
	var plain Plain
	if err := value.Decode(&plain); err != nil {
		return fmt.Errorf("unmarshal Inner: %w", err)
	}
	*j = Inner(plain)
	return nil
}
