// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT.

package test
import "encoding/json"

type Case struct {
	// CapitalCamelField corresponds to the JSON schema field "CapitalCamelField".
	CapitalCamelField *string `json:"CapitalCamelField,omitempty"`

	// UPPERCASEFIELD corresponds to the JSON schema field "UPPERCASEFIELD".
	UPPERCASEFIELD *string `json:"UPPERCASEFIELD,omitempty"`

	// CamelCase corresponds to the JSON schema field "camelCase".
	CamelCase *string `json:"camelCase,omitempty"`

	// Lowercase corresponds to the JSON schema field "lowercase".
	Lowercase *string `json:"lowercase,omitempty"`

	// SnakeMixedCase corresponds to the JSON schema field "snake_Mixed_Case".
	SnakeMixedCase *string `json:"snake_Mixed_Case,omitempty"`

	// SnakeCase corresponds to the JSON schema field "snake_case".
	SnakeCase *string `json:"snake_case,omitempty"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Case) UnmarshalJSON(b []byte) error {
	var v struct {
		Case
	}
	if err := json.Unmarshal(b, &v); err != nil {
		return err
	}
	*j = v.Case
	return nil
}

