// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package test

import "encoding/json"
import "fmt"
import yaml "gopkg.in/yaml.v3"
import "reflect"

// Discriminator values and a field name carrying a quote, a backslash and a
// percent sign, which the generated error literals must escape.
type EscapedText struct {
	// Kind corresponds to the JSON schema field "kind".
	Kind EscapedTextKind `json:"kind" yaml:"kind" mapstructure:"kind"`

	// XY corresponds to the JSON schema field "x%y".
	XY *string `json:"x%y,omitempty,omitzero" yaml:"x%y,omitempty" mapstructure:"x%y,omitempty"`

	// Z corresponds to the JSON schema field "z".
	Z *string `json:"z,omitempty,omitzero" yaml:"z,omitempty" mapstructure:"z,omitempty"`
}

type EscapedTextKind string

const EscapedTextKindAB EscapedTextKind = "a\"b"
const EscapedTextKindCD EscapedTextKind = "c%d"
const EscapedTextKindEF EscapedTextKind = "e\\f"
const EscapedTextKindG EscapedTextKind = "g"

var enumValues_EscapedTextKind = []interface{}{
	"a\"b",
	"c%d",
	"e\\f",
	"g",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *EscapedTextKind) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_EscapedTextKind {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_EscapedTextKind, v)
	}
	*j = EscapedTextKind(v)
	return nil
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *EscapedTextKind) UnmarshalYAML(value *yaml.Node) error {
	var v string
	if err := value.Decode(&v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_EscapedTextKind {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_EscapedTextKind, v)
	}
	*j = EscapedTextKind(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *EscapedText) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return fmt.Errorf("unmarshal raw EscapedText: %w", err)
	}
	if _, ok := raw["kind"]; raw != nil && !ok {
		return fmt.Errorf("field kind in EscapedText: required")
	}
	rawDisc, hasDisc := raw["kind"]
	if hasDisc {
		discStr, isStr := rawDisc.(string)
		if !isStr {
			return fmt.Errorf("field kind in EscapedText: must be a string for discriminator dispatch")
		}
		if discStr == "a\"b" {
			if _, ok := raw["x%y"]; !ok {
				return fmt.Errorf("field x%%y in EscapedText (when kind='a\"b'): required")
			}
		}
		if discStr == "c%d" || discStr == "e\\f" {
			if _, ok := raw["x%y"]; !ok {
				return fmt.Errorf("field x%%y in EscapedText (when kind='%s'): required", discStr)
			}
		} else {
			if _, ok := raw["z"]; !ok {
				return fmt.Errorf("field z in EscapedText (when kind not in [c%%d, e\\f]): required")
			}
		}
	}
	type Plain EscapedText
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return fmt.Errorf("unmarshal EscapedText: %w", err)
	}
	*j = EscapedText(plain)
	return nil
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *EscapedText) UnmarshalYAML(value *yaml.Node) error {
	var raw map[string]interface{}
	if err := value.Decode(&raw); err != nil {
		return fmt.Errorf("unmarshal raw EscapedText: %w", err)
	}
	if _, ok := raw["kind"]; raw != nil && !ok {
		return fmt.Errorf("field kind in EscapedText: required")
	}
	rawDisc, hasDisc := raw["kind"]
	if hasDisc {
		discStr, isStr := rawDisc.(string)
		if !isStr {
			return fmt.Errorf("field kind in EscapedText: must be a string for discriminator dispatch")
		}
		if discStr == "a\"b" {
			if _, ok := raw["x%y"]; !ok {
				return fmt.Errorf("field x%%y in EscapedText (when kind='a\"b'): required")
			}
		}
		if discStr == "c%d" || discStr == "e\\f" {
			if _, ok := raw["x%y"]; !ok {
				return fmt.Errorf("field x%%y in EscapedText (when kind='%s'): required", discStr)
			}
		} else {
			if _, ok := raw["z"]; !ok {
				return fmt.Errorf("field z in EscapedText (when kind not in [c%%d, e\\f]): required")
			}
		}
	}
	type Plain EscapedText
	var plain Plain
	if err := value.Decode(&plain); err != nil {
		return fmt.Errorf("unmarshal EscapedText: %w", err)
	}
	*j = EscapedText(plain)
	return nil
}
