---
version: 2
project_name: go-jsonschema
before:
  hooks:
    - go mod tidy
builds:
  - main: main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.gitCommit={{.Commit}}
      - -X main.buildTime={{.Date}}
      - -X main.goVersion={{.Env.GO_VERSION}}
      - -X main.osArch={{.Arch}}
archives:
  - name_template: '{{ .ProjectName }}_ {{- title .Os }}_ {{- if eq .Arch "amd64" }}x86_64 {{- else if eq .Arch "386" }}i386 {{- else }}{{ .Arch }}{{ end }}' # yamllint disable-line rule:line-length
checksum:
  name_template: checksums.txt
snapshot:
  version_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
release:
  github:
    owner: omissis
    name: go-jsonschema
  name_template: "{{ .Tag }}"
  prerelease: auto
homebrew_casks:
  - name: go-jsonschema
    description: go-jsonschema binary
    url:
      verified: github.com/omissis/go-jsonschema
    homepage: https://github.com/omissis/go-jsonschema
    repository:
      owner: omissis
      name: homebrew-go-jsonschema
    skip_upload: auto
    hooks:
      post:
        install: |
          if OS.mac?
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/go-jsonschema"]
          end

dockers_v2:
  - images:
      - "omissis/go-jsonschema"
    flags:
      - "--target=go-jsonschema"
    tags:
      - "v{{ .Version }}"
      - "{{ if .IsNightly }}nightly{{ end }}"
      - "{{ if not .IsNightly }}latest{{ end }}"
    labels:
      "org.opencontainers.image.description": "A tool to generate Go data types from JSON Schema definitions."
      "org.opencontainers.image.created": "{{.Date}}"
      "org.opencontainers.image.name": "{{.ProjectName}}"
      "org.opencontainers.image.revision": "{{.FullCommit}}"
      "org.opencontainers.image.version": "{{.Version}}"
      "org.opencontainers.image.source": "{{.GitURL}}"
