distro: trusty
language: go
go:
- '1.16.3'
env:
- GO111MODULE=on
script:
- go get github.com/mitchellh/gox
- go mod download
- go test ./...
- gox -osarch="darwin/amd64 linux/amd64 linux/arm windows/amd64" -output="bin/gojsonschema-{{.OS}}-{{.Arch}}" ./cmd/...
deploy:
  provider: releases
  api_key:
    secure: "MSr8NnBOvAnz6/ILqbJxbfiJKdkrjVL+vZ8q3EySn0zeSHoz64LguPIA1C8ZkFHneIGWvFTSjPxGhv5Rx/cdXLbcLXZaCz5Vn7C5+i66tJ1naPBPeR1XoOS83TDBj8eoMS94PYg7/ukdqX4DZ8eoTVCVgBDvR19sF3ow5hDWj9AacBU0RlX9nfAXFTGVBPlx9OwUykA22eFWT8JzKLsbm/gnk/KtMte93Jlo6Ka0xEowJvhXa1mGaAT2i8hetUu8BPBTsTLUjkiStkVPx6n6YwRWq6QBugkl5QxXhZ5CC2W5boIiw60fEnizqVRG++lX1ILqSHY5Ngz7BWoAhpnqVft8uxBjDjpbfvDm2yzMALfljtTuQHJ4Z1RIGC9hJ9mGlsFXIQHaxje9//uofBI52Dx9dgsu0MDETFh7z8BM4UFLTMW3cEVRYj8XifODdd1aK2MaCJZJMDBzymKLIHZo1XHSeMRoj3Nn4qZJ4OT9eARd0wh10PRyOVDOojn/oN/qFYDPnR2ur3Ul5BkvyFnCckIstb0CflYg3Q5ZYlJdlIp+4q6x/GS8otDz8Lq7FUGs3GwNQ0eOE87VyLvSKEpoauPAuC/FYYKampAryHjjzN10NquuLYeY0+BzvY7mc5NzaP0TR5QuyxILfhNhC9l4XRXhBJbVhZHzfnJTJPVnVlk="
  file_glob: true
  file: 'bin/*'
  skip_cleanup: true
  on:
    tags: true
