// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package test

import "bytes"
import "encoding/json"
import "fmt"
import yaml "gopkg.in/yaml.v3"

type WithNull struct {
	// Value corresponds to the JSON schema field "value".
	Value WithNullValue `json:"value" yaml:"value" mapstructure:"value"`
}

type WithNullValue struct {
	value interface{}
}

// AsString returns the value as a string and reports whether it was a string.
func (j *WithNullValue) AsString() (string, bool) {
	if j == nil {
		return "", false
	}
	v, ok := j.value.(string)
	return v, ok
}

// IsNull reports whether the decoded value was an explicit JSON null.
func (j *WithNullValue) IsNull() bool {
	return j == nil || j.value == nil
}

// IsZero reports whether the value is unset; supports the encoding/json `omitzero`
// tag.
func (j *WithNullValue) IsZero() bool {
	if j == nil {
		return true
	}
	return j.value == nil
}

// MarshalJSON implements json.Marshaler.
func (j *WithNullValue) MarshalJSON() ([]byte, error) {
	if j == nil || j.value == nil {
		return []byte("null"), nil
	}
	return json.Marshal(j.value)
}

// MarshalYAML implements yaml.Marshaler.
func (j *WithNullValue) MarshalYAML() (interface{}, error) {
	if j == nil {
		return nil, nil
	}
	return j.value, nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *WithNullValue) UnmarshalJSON(value []byte) error {
	dec := json.NewDecoder(bytes.NewReader(value))
	tok, err := dec.Token()
	if err != nil {
		return err
	}
	switch tok.(type) {
	case string:
		var v string
		if err := json.Unmarshal(value, &v); err != nil {
			return err
		}
		j.value = v
	case nil:
		j.value = nil
	default:
		return fmt.Errorf("WithNullValue: unsupported JSON value of type %T", tok)
	}
	return nil
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *WithNullValue) UnmarshalYAML(value *yaml.Node) error {
	if value.Kind != yaml.ScalarNode {
		return fmt.Errorf("WithNullValue: expected scalar YAML node")
	}
	switch value.Tag {
	case "!!str":
		var v string
		if err := value.Decode(&v); err != nil {
			return err
		}
		j.value = v
	case "!!null":
		j.value = nil
	default:
		return fmt.Errorf("WithNullValue: unsupported YAML scalar tag %q", value.Tag)
	}
	return nil
}

// Value returns the decoded primitive payload.
func (j *WithNullValue) Value() any {
	if j == nil {
		return nil
	}
	return j.value
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *WithNull) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return fmt.Errorf("unmarshal raw WithNull: %w", err)
	}
	if _, ok := raw["value"]; raw != nil && !ok {
		return fmt.Errorf("field value in WithNull: required")
	}
	type Plain WithNull
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return fmt.Errorf("unmarshal WithNull: %w", err)
	}
	*j = WithNull(plain)
	return nil
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *WithNull) UnmarshalYAML(value *yaml.Node) error {
	var raw map[string]interface{}
	if err := value.Decode(&raw); err != nil {
		return fmt.Errorf("unmarshal raw WithNull: %w", err)
	}
	if _, ok := raw["value"]; raw != nil && !ok {
		return fmt.Errorf("field value in WithNull: required")
	}
	type Plain WithNull
	var plain Plain
	if err := value.Decode(&plain); err != nil {
		return fmt.Errorf("unmarshal WithNull: %w", err)
	}
	*j = WithNull(plain)
	return nil
}
