// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package test

import "bytes"
import "encoding/json"
import "fmt"
import yaml "gopkg.in/yaml.v3"

type EmbeddedInStruct struct {
	// Label corresponds to the JSON schema field "label".
	Label string `json:"label" yaml:"label" mapstructure:"label"`

	// ValueOptional corresponds to the JSON schema field "valueOptional".
	ValueOptional *EmbeddedInStructValueOptional `json:"valueOptional,omitempty,omitzero" yaml:"valueOptional,omitempty" mapstructure:"valueOptional,omitempty"`
}

type EmbeddedInStructValueOptional struct {
	value interface{}

	present bool
}

// AsBool returns the value as a bool and reports whether it was a bool.
func (j *EmbeddedInStructValueOptional) AsBool() (bool, bool) {
	if j == nil || !j.present {
		return false, false
	}
	v, ok := j.value.(bool)
	return v, ok
}

// AsNumber returns the value as a float64 and reports whether it was numeric.
func (j *EmbeddedInStructValueOptional) AsNumber() (float64, bool) {
	if j == nil || !j.present {
		return 0, false
	}
	v, ok := j.value.(float64)
	return v, ok
}

// AsString returns the value as a string and reports whether it was a string.
func (j *EmbeddedInStructValueOptional) AsString() (string, bool) {
	if j == nil || !j.present {
		return "", false
	}
	v, ok := j.value.(string)
	return v, ok
}

// IsZero reports whether the wrapper has not been populated by
// Unmarshal{JSON,YAML}; supports the encoding/json `omitzero` tag.
func (j *EmbeddedInStructValueOptional) IsZero() bool {
	return j == nil || !j.present
}

// MarshalJSON implements json.Marshaler.
func (j *EmbeddedInStructValueOptional) MarshalJSON() ([]byte, error) {
	if j == nil || !j.present {
		return nil, fmt.Errorf("EmbeddedInStructValueOptional: cannot marshal unset value (schema does not allow null)")
	}
	if j.value == nil {
		return nil, fmt.Errorf("EmbeddedInStructValueOptional: cannot marshal nil value (schema does not allow null)")
	}
	return json.Marshal(j.value)
}

// MarshalYAML implements yaml.Marshaler.
func (j *EmbeddedInStructValueOptional) MarshalYAML() (interface{}, error) {
	if j == nil || !j.present {
		return nil, fmt.Errorf("EmbeddedInStructValueOptional: cannot marshal unset value (schema does not allow null)")
	}
	if j.value == nil {
		return nil, fmt.Errorf("EmbeddedInStructValueOptional: cannot marshal nil value (schema does not allow null)")
	}
	return j.value, nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *EmbeddedInStructValueOptional) UnmarshalJSON(value []byte) error {
	dec := json.NewDecoder(bytes.NewReader(value))
	dec.UseNumber()
	tok, err := dec.Token()
	if err != nil {
		return err
	}
	switch tok.(type) {
	case string:
		var v string
		if err := json.Unmarshal(value, &v); err != nil {
			return err
		}
		j.value = v
	case json.Number:
		var v float64
		if err := json.Unmarshal(value, &v); err != nil {
			return err
		}
		j.value = v
	case bool:
		var v bool
		if err := json.Unmarshal(value, &v); err != nil {
			return err
		}
		j.value = v
	default:
		return fmt.Errorf("EmbeddedInStructValueOptional: unsupported JSON value of type %T", tok)
	}
	j.present = true
	return nil
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *EmbeddedInStructValueOptional) UnmarshalYAML(value *yaml.Node) error {
	if value.Kind != yaml.ScalarNode {
		return fmt.Errorf("EmbeddedInStructValueOptional: expected scalar YAML node")
	}
	switch value.Tag {
	case "!!str":
		var v string
		if err := value.Decode(&v); err != nil {
			return err
		}
		j.value = v
	case "!!int", "!!float":
		var v float64
		if err := value.Decode(&v); err != nil {
			return err
		}
		j.value = v
	case "!!bool":
		var v bool
		if err := value.Decode(&v); err != nil {
			return err
		}
		j.value = v
	default:
		return fmt.Errorf("EmbeddedInStructValueOptional: unsupported YAML scalar tag %q", value.Tag)
	}
	j.present = true
	return nil
}

// Value returns the decoded primitive payload.
func (j *EmbeddedInStructValueOptional) Value() any {
	if j == nil {
		return nil
	}
	return j.value
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *EmbeddedInStruct) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return fmt.Errorf("unmarshal raw EmbeddedInStruct: %w", err)
	}
	if _, ok := raw["label"]; raw != nil && !ok {
		return fmt.Errorf("field label in EmbeddedInStruct: required")
	}
	type Plain EmbeddedInStruct
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return fmt.Errorf("unmarshal EmbeddedInStruct: %w", err)
	}
	*j = EmbeddedInStruct(plain)
	return nil
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *EmbeddedInStruct) UnmarshalYAML(value *yaml.Node) error {
	var raw map[string]interface{}
	if err := value.Decode(&raw); err != nil {
		return fmt.Errorf("unmarshal raw EmbeddedInStruct: %w", err)
	}
	if _, ok := raw["label"]; raw != nil && !ok {
		return fmt.Errorf("field label in EmbeddedInStruct: required")
	}
	type Plain EmbeddedInStruct
	var plain Plain
	if err := value.Decode(&plain); err != nil {
		return fmt.Errorf("unmarshal EmbeddedInStruct: %w", err)
	}
	*j = EmbeddedInStruct(plain)
	return nil
}
