// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package test

type Name string

type RefExternalFileAllOfNestedRefs struct {
	// Name corresponds to the JSON schema field "name".
	Name *Name `json:"name,omitempty" yaml:"name,omitempty" mapstructure:"name,omitempty"`
}

type RefNested struct {
	// MyThing corresponds to the JSON schema field "myThing".
	MyThing *Thing `json:"myThing,omitempty" yaml:"myThing,omitempty" mapstructure:"myThing,omitempty"`
}

type Thing struct {
	// Name corresponds to the JSON schema field "name".
	Name *Name `json:"name,omitempty" yaml:"name,omitempty" mapstructure:"name,omitempty"`
}
