// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package test

import "encoding/json"
import "fmt"
import yaml "gopkg.in/yaml.v3"

type IntegerFormatPrecedence struct {
	// --min-sized-ints derives the width from the declared bounds, which is strictly
	// more information than the format hint, so it wins over `format: int64` here.
	Bounded *uint8 `json:"bounded,omitempty,omitzero" yaml:"bounded,omitempty" mapstructure:"bounded,omitempty"`

	// With no bounds to derive from, --min-sized-ints already widens to int64, so the
	// format changes nothing.
	Unbounded *int64 `json:"unbounded,omitempty,omitzero" yaml:"unbounded,omitempty" mapstructure:"unbounded,omitempty"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *IntegerFormatPrecedence) UnmarshalJSON(value []byte) error {
	type Plain IntegerFormatPrecedence
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if plain.Bounded != nil && 100 < *plain.Bounded {
		return fmt.Errorf("field %s: must be <= %v", "bounded", 100)
	}
	*j = IntegerFormatPrecedence(plain)
	return nil
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *IntegerFormatPrecedence) UnmarshalYAML(value *yaml.Node) error {
	type Plain IntegerFormatPrecedence
	var plain Plain
	if err := value.Decode(&plain); err != nil {
		return err
	}
	if plain.Bounded != nil && 100 < *plain.Bounded {
		return fmt.Errorf("field %s: must be <= %v", "bounded", 100)
	}
	*j = IntegerFormatPrecedence(plain)
	return nil
}
