// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package test

type PropertylessVariants struct {
	// Generated with DisableCustomTypesForMaps, which makes an object variant without
	// properties an inline map. The holder needs a named type per variant, so the
	// generic type stays; generation used to fail.
	Kernel interface{} `json:"kernel,omitempty,omitzero" yaml:"kernel,omitempty" mapstructure:"kernel,omitempty"`
}
