// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package test

import "encoding/json"
import "fmt"
import yaml "gopkg.in/yaml.v3"
import "time"
import "unicode/utf8"

type NullablePrimitives struct {
	// Count corresponds to the JSON schema field "count".
	Count *int `json:"count,omitempty,omitzero" yaml:"count,omitempty" mapstructure:"count,omitempty"`

	// Enabled corresponds to the JSON schema field "enabled".
	Enabled *bool `json:"enabled,omitempty,omitzero" yaml:"enabled,omitempty" mapstructure:"enabled,omitempty"`

	// Label corresponds to the JSON schema field "label".
	Label *string `json:"label,omitempty,omitzero" yaml:"label,omitempty" mapstructure:"label,omitempty"`

	// Objects keep their named struct and are wrapped in a pointer, which is
	// unchanged.
	Meta *NullablePrimitivesMeta `json:"meta,omitempty,omitzero" yaml:"meta,omitempty" mapstructure:"meta,omitempty"`

	// Same for string constraints: `minLength` was silently dropped.
	Name *string `json:"name,omitempty,omitzero" yaml:"name,omitempty" mapstructure:"name,omitempty"`

	// Already a plain *time.Time before this change, via the temporal special case
	// added upstream in #570 / #607.
	ObservedAt *time.Time `json:"observedAt,omitempty,omitzero" yaml:"observedAt,omitempty" mapstructure:"observedAt,omitempty"`

	// A nullable primitive becomes a plain *float64. The alias form `type X *float64`
	// is a named POINTER type, which Go rejects as a method receiver, so the name
	// could never carry UnmarshalJSON or validation.
	OilRate *float64 `json:"oilRate,omitempty,omitzero" yaml:"oilRate,omitempty" mapstructure:"oilRate,omitempty"`

	// A nullable primitive carrying a constraint. Before this change the alias path
	// emitted no UnmarshalJSON at all, so `minimum` was silently dropped and never
	// enforced.
	Score *int `json:"score,omitempty,omitzero" yaml:"score,omitempty" mapstructure:"score,omitempty"`

	// Arrays keep their named type: `type X []string` is not a pointer type and can
	// take methods, so the name is not dead weight.
	Tags *NullablePrimitivesTags `json:"tags,omitempty,omitzero" yaml:"tags,omitempty" mapstructure:"tags,omitempty"`
}

// Objects keep their named struct and are wrapped in a pointer, which is
// unchanged.
type NullablePrimitivesMeta struct {
	// A corresponds to the JSON schema field "a".
	A *string `json:"a,omitempty,omitzero" yaml:"a,omitempty" mapstructure:"a,omitempty"`
}

// Arrays keep their named type: `type X []string` is not a pointer type and can
// take methods, so the name is not dead weight.
type NullablePrimitivesTags []string

// UnmarshalJSON implements json.Unmarshaler.
func (j *NullablePrimitives) UnmarshalJSON(value []byte) error {
	type Plain NullablePrimitives
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return fmt.Errorf("unmarshal NullablePrimitives: %w", err)
	}
	if plain.Name != nil && utf8.RuneCountInString(string(*plain.Name)) < 3 {
		return fmt.Errorf("field %s length: must be >= %d", "name", 3)
	}
	if plain.Score != nil && 5 > *plain.Score {
		return fmt.Errorf("field %s: must be >= %v", "score", 5)
	}
	*j = NullablePrimitives(plain)
	return nil
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *NullablePrimitives) UnmarshalYAML(value *yaml.Node) error {
	type Plain NullablePrimitives
	var plain Plain
	if err := value.Decode(&plain); err != nil {
		return fmt.Errorf("unmarshal NullablePrimitives: %w", err)
	}
	if plain.Name != nil && utf8.RuneCountInString(string(*plain.Name)) < 3 {
		return fmt.Errorf("field %s length: must be >= %d", "name", 3)
	}
	if plain.Score != nil && 5 > *plain.Score {
		return fmt.Errorf("field %s: must be >= %v", "score", 5)
	}
	*j = NullablePrimitives(plain)
	return nil
}
