// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package test

import "encoding/json"
import "fmt"
import yaml "gopkg.in/yaml.v3"
import "regexp"

type Regex struct {
	// Pattern corresponds to the JSON schema field "pattern".
	Pattern string `json:"pattern" yaml:"pattern" mapstructure:"pattern"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Regex) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return fmt.Errorf("unmarshal raw Regex: %w", err)
	}
	if _, ok := raw["pattern"]; raw != nil && !ok {
		return fmt.Errorf("field pattern in Regex: required")
	}
	type Plain Regex
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if _, err := regexp.Compile(string(plain.Pattern)); err != nil {
		return fmt.Errorf("field %s: must be a valid RE2 regular expression: %w", "pattern", err)
	}
	*j = Regex(plain)
	return nil
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *Regex) UnmarshalYAML(value *yaml.Node) error {
	var raw map[string]interface{}
	if err := value.Decode(&raw); err != nil {
		return fmt.Errorf("unmarshal raw Regex: %w", err)
	}
	if _, ok := raw["pattern"]; raw != nil && !ok {
		return fmt.Errorf("field pattern in Regex: required")
	}
	type Plain Regex
	var plain Plain
	if err := value.Decode(&plain); err != nil {
		return err
	}
	if _, err := regexp.Compile(string(plain.Pattern)); err != nil {
		return fmt.Errorf("field %s: must be a valid RE2 regular expression: %w", "pattern", err)
	}
	*j = Regex(plain)
	return nil
}
