// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package test

type Choice interface{}

type Choice1 struct {
	// B corresponds to the JSON schema field "b".
	B *int `json:"b,omitempty,omitzero" yaml:"b,omitempty" mapstructure:"b,omitempty"`
}

type NestedRefsArray struct {
	// Item corresponds to the JSON schema field "item".
	Item *Wrapper_1 `json:"item,omitempty,omitzero" yaml:"item,omitempty" mapstructure:"item,omitempty"`

	// Variant corresponds to the JSON schema field "variant".
	Variant *Choice1 `json:"variant,omitempty,omitzero" yaml:"variant,omitempty" mapstructure:"variant,omitempty"`
}

type Wrapper []struct {
	// Name corresponds to the JSON schema field "name".
	Name *string `json:"name,omitempty,omitzero" yaml:"name,omitempty" mapstructure:"name,omitempty"`
}

type Wrapper_1 struct {
	// Name corresponds to the JSON schema field "name".
	Name *string `json:"name,omitempty,omitzero" yaml:"name,omitempty" mapstructure:"name,omitempty"`
}
