// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package test

type Foo struct {
	// Bar corresponds to the JSON schema field "bar".
	Bar *string `json:"bar,omitempty,omitzero" yaml:"bar,omitempty" mapstructure:"bar,omitempty"`

	// A member legitimately NAMED `items`. Dropping segments by text cannot tell this
	// from the keyword, so the name would be lost and this subschema would collide
	// with a sibling.
	Items *FooItems `json:"items,omitempty,omitzero" yaml:"items,omitempty" mapstructure:"items,omitempty"`
}

type FooBar string

// A member legitimately NAMED `items`. Dropping segments by text cannot tell this
// from the keyword, so the name would be lost and this subschema would collide
// with a sibling.
type FooItems struct {
	// Bar corresponds to the JSON schema field "bar".
	Bar *float64 `json:"bar,omitempty,omitzero" yaml:"bar,omitempty" mapstructure:"bar,omitempty"`
}

type FooItemsBar float64

type KwWrapper []struct {
	// Bar corresponds to the JSON schema field "bar".
	Bar *string `json:"bar,omitempty,omitzero" yaml:"bar,omitempty" mapstructure:"bar,omitempty"`
}

type KwWrapperItemsBar string

type NestedRefsKeywordNames struct {
	// Nested corresponds to the JSON schema field "nested".
	Nested *FooItemsBar `json:"nested,omitempty,omitzero" yaml:"nested,omitempty" mapstructure:"nested,omitempty"`

	// Sibling corresponds to the JSON schema field "sibling".
	Sibling *FooBar `json:"sibling,omitempty,omitzero" yaml:"sibling,omitempty" mapstructure:"sibling,omitempty"`

	// A path continuing past a single-schema `items`. Only the tuple form consumes
	// what follows, so `items` is kept and the trailing `properties` dropped —
	// swallowing the next segment would name this after `properties` instead.
	ThroughItems *KwWrapperItemsBar `json:"throughItems,omitempty,omitzero" yaml:"throughItems,omitempty" mapstructure:"throughItems,omitempty"`
}
