// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package test

type DepHolder struct {
	// Flag corresponds to the JSON schema field "flag".
	Flag *string `json:"flag,omitempty,omitzero" yaml:"flag,omitempty" mapstructure:"flag,omitempty"`
}

type DepHolderNeedsFlag struct {
	// Extra corresponds to the JSON schema field "extra".
	Extra *string `json:"extra,omitempty,omitzero" yaml:"extra,omitempty" mapstructure:"extra,omitempty"`
}

type NestedRefsDependencies struct {
	// Draft-07 `dependencies` is dual-form; the schema form parses into
	// DependentSchemas, so a $ref descending through it resolves there. A
	// property-name dependency lands in DependentRequired instead, is not a schema,
	// and correctly finds nothing.
	ViaDependencies *DepHolderNeedsFlag `json:"viaDependencies,omitempty,omitzero" yaml:"viaDependencies,omitempty" mapstructure:"viaDependencies,omitempty"`
}
