// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package test

type Holder struct {
	// Inner corresponds to the JSON schema field "inner".
	Inner *HolderInner `json:"inner,omitempty,omitzero" yaml:"inner,omitempty" mapstructure:"inner,omitempty"`
}

type HolderInner struct {
	// X corresponds to the JSON schema field "x".
	X *string `json:"x,omitempty,omitzero" yaml:"x,omitempty" mapstructure:"x,omitempty"`
}

type HolderNested struct {
	// Y corresponds to the JSON schema field "y".
	Y *int `json:"y,omitempty,omitzero" yaml:"y,omitempty" mapstructure:"y,omitempty"`
}

type NestedRefs struct {
	// Direct corresponds to the JSON schema field "direct".
	Direct *Holder `json:"direct,omitempty,omitzero" yaml:"direct,omitempty" mapstructure:"direct,omitempty"`

	// IntoDef corresponds to the JSON schema field "intoDef".
	IntoDef *HolderNested `json:"intoDef,omitempty,omitzero" yaml:"intoDef,omitempty" mapstructure:"intoDef,omitempty"`

	// IntoProp corresponds to the JSON schema field "intoProp".
	IntoProp *HolderInner `json:"intoProp,omitempty,omitzero" yaml:"intoProp,omitempty" mapstructure:"intoProp,omitempty"`
}
