// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package test

type AddlTrue struct {
	// Title corresponds to the JSON schema field "title".
	Title *string `json:"title,omitempty,omitzero" yaml:"title,omitempty" mapstructure:"title,omitempty"`

	AdditionalProperties interface{} `mapstructure:",remain"`
}
