// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package test

import "bytes"
import "encoding/json"
import "fmt"
import yaml "gopkg.in/yaml.v3"
import "regexp"

type OneOfVariant struct {
	// With format validation enabled the check runs at the end of the wrapper's
	// string branch, against the value it just decoded — the same check, from the
	// same validator, as the non-oneOf path emits.
	IdOrNumber *OneOfVariantIdOrNumber `json:"idOrNumber,omitempty,omitzero" yaml:"idOrNumber,omitempty" mapstructure:"idOrNumber,omitempty"`

	// The non-oneOf path, for comparison: same schema declaration, same check.
	PlainUuid *string `json:"plainUuid,omitempty,omitzero" yaml:"plainUuid,omitempty" mapstructure:"plainUuid,omitempty"`
}

// With format validation enabled the check runs at the end of the wrapper's string
// branch, against the value it just decoded — the same check, from the same
// validator, as the non-oneOf path emits.
type OneOfVariantIdOrNumber struct {
	value interface{}

	present bool
}

// AsNumber returns the value as a float64 and reports whether it was numeric.
func (j *OneOfVariantIdOrNumber) AsNumber() (float64, bool) {
	if j == nil || !j.present {
		return 0, false
	}
	v, ok := j.value.(float64)
	return v, ok
}

// AsString returns the value as a string and reports whether it was a string.
func (j *OneOfVariantIdOrNumber) AsString() (string, bool) {
	if j == nil || !j.present {
		return "", false
	}
	v, ok := j.value.(string)
	return v, ok
}

// IsZero reports whether the wrapper has not been populated by
// Unmarshal{JSON,YAML}; supports the encoding/json `omitzero` tag. Note: an
// explicitly-decoded JSON `null` is NOT zero — see IsNull.
func (j *OneOfVariantIdOrNumber) IsZero() bool {
	return j == nil || !j.present
}

// MarshalJSON implements json.Marshaler.
func (j *OneOfVariantIdOrNumber) MarshalJSON() ([]byte, error) {
	if j == nil || !j.present {
		return nil, fmt.Errorf("OneOfVariantIdOrNumber: cannot marshal unset value (schema does not allow null)")
	}
	if j.value == nil {
		return nil, fmt.Errorf("OneOfVariantIdOrNumber: cannot marshal nil value (schema does not allow null)")
	}
	return json.Marshal(j.value)
}

// MarshalYAML implements yaml.Marshaler.
func (j *OneOfVariantIdOrNumber) MarshalYAML() (interface{}, error) {
	if j == nil || !j.present {
		return nil, fmt.Errorf("OneOfVariantIdOrNumber: cannot marshal unset value (schema does not allow null)")
	}
	if j.value == nil {
		return nil, fmt.Errorf("OneOfVariantIdOrNumber: cannot marshal nil value (schema does not allow null)")
	}
	return j.value, nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *OneOfVariantIdOrNumber) UnmarshalJSON(value []byte) error {
	dec := json.NewDecoder(bytes.NewReader(value))
	dec.UseNumber()
	tok, err := dec.Token()
	if err != nil {
		return err
	}
	switch tok.(type) {
	case string:
		var v string
		if err := json.Unmarshal(value, &v); err != nil {
			return err
		}
		if !regexpFormatUUID.MatchString(string(v)) {
			return fmt.Errorf("field %s: must be a valid uuid", "OneOfVariantIdOrNumber")
		}
		j.value = v
	case json.Number:
		var v float64
		if err := json.Unmarshal(value, &v); err != nil {
			return err
		}
		j.value = v
	default:
		return fmt.Errorf("OneOfVariantIdOrNumber: unsupported JSON value of type %T", tok)
	}
	j.present = true
	return nil
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *OneOfVariantIdOrNumber) UnmarshalYAML(value *yaml.Node) error {
	if value.Kind != yaml.ScalarNode {
		return fmt.Errorf("OneOfVariantIdOrNumber: expected scalar YAML node")
	}
	switch value.Tag {
	case "!!str":
		var v string
		if err := value.Decode(&v); err != nil {
			return err
		}
		if !regexpFormatUUID.MatchString(string(v)) {
			return fmt.Errorf("field %s: must be a valid uuid", "OneOfVariantIdOrNumber")
		}
		j.value = v
	case "!!int", "!!float":
		var v float64
		if err := value.Decode(&v); err != nil {
			return err
		}
		j.value = v
	default:
		return fmt.Errorf("OneOfVariantIdOrNumber: unsupported YAML scalar tag %q", value.Tag)
	}
	j.present = true
	return nil
}

// Value returns the decoded primitive payload.
func (j *OneOfVariantIdOrNumber) Value() any {
	if j == nil {
		return nil
	}
	return j.value
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *OneOfVariant) UnmarshalJSON(value []byte) error {
	type Plain OneOfVariant
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return fmt.Errorf("unmarshal OneOfVariant: %w", err)
	}
	if plain.PlainUuid != nil {
		if !regexpFormatUUID.MatchString(string(*plain.PlainUuid)) {
			return fmt.Errorf("field %s: must be a valid uuid", "plainUuid")
		}
	}
	*j = OneOfVariant(plain)
	return nil
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *OneOfVariant) UnmarshalYAML(value *yaml.Node) error {
	type Plain OneOfVariant
	var plain Plain
	if err := value.Decode(&plain); err != nil {
		return fmt.Errorf("unmarshal OneOfVariant: %w", err)
	}
	if plain.PlainUuid != nil {
		if !regexpFormatUUID.MatchString(string(*plain.PlainUuid)) {
			return fmt.Errorf("field %s: must be a valid uuid", "plainUuid")
		}
	}
	*j = OneOfVariant(plain)
	return nil
}

var regexpFormatUUID = regexp.MustCompile(`^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$`)
