// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package test

import "encoding/json"
import "fmt"
import yaml "gopkg.in/yaml.v3"

type RootOneOfDiscriminator struct {
	Ping *RootOneOfDiscriminatorPing `json:"-" yaml:"-"`

	Pong *RootOneOfDiscriminatorPong `json:"-" yaml:"-"`
}

type RootOneOfDiscriminatorPing struct {
	// Kind corresponds to the JSON schema field "kind".
	Kind string `json:"kind" yaml:"kind" mapstructure:"kind"`

	// Ttl corresponds to the JSON schema field "ttl".
	Ttl int `json:"ttl" yaml:"ttl" mapstructure:"ttl"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *RootOneOfDiscriminatorPing) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return fmt.Errorf("unmarshal raw RootOneOfDiscriminatorPing: %w", err)
	}
	if _, ok := raw["kind"]; raw != nil && !ok {
		return fmt.Errorf("field kind in RootOneOfDiscriminatorPing: required")
	}
	if _, ok := raw["ttl"]; raw != nil && !ok {
		return fmt.Errorf("field ttl in RootOneOfDiscriminatorPing: required")
	}
	type Plain RootOneOfDiscriminatorPing
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return fmt.Errorf("unmarshal RootOneOfDiscriminatorPing: %w", err)
	}
	if plain.Kind != "ping" {
		return fmt.Errorf("field %s: must be equal to %s", "kind", "ping")
	}
	*j = RootOneOfDiscriminatorPing(plain)
	return nil
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *RootOneOfDiscriminatorPing) UnmarshalYAML(value *yaml.Node) error {
	var raw map[string]interface{}
	if err := value.Decode(&raw); err != nil {
		return fmt.Errorf("unmarshal raw RootOneOfDiscriminatorPing: %w", err)
	}
	if _, ok := raw["kind"]; raw != nil && !ok {
		return fmt.Errorf("field kind in RootOneOfDiscriminatorPing: required")
	}
	if _, ok := raw["ttl"]; raw != nil && !ok {
		return fmt.Errorf("field ttl in RootOneOfDiscriminatorPing: required")
	}
	type Plain RootOneOfDiscriminatorPing
	var plain Plain
	if err := value.Decode(&plain); err != nil {
		return fmt.Errorf("unmarshal RootOneOfDiscriminatorPing: %w", err)
	}
	if plain.Kind != "ping" {
		return fmt.Errorf("field %s: must be equal to %s", "kind", "ping")
	}
	*j = RootOneOfDiscriminatorPing(plain)
	return nil
}

type RootOneOfDiscriminatorPong struct {
	// Echo corresponds to the JSON schema field "echo".
	Echo string `json:"echo" yaml:"echo" mapstructure:"echo"`

	// Kind corresponds to the JSON schema field "kind".
	Kind string `json:"kind" yaml:"kind" mapstructure:"kind"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *RootOneOfDiscriminatorPong) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return fmt.Errorf("unmarshal raw RootOneOfDiscriminatorPong: %w", err)
	}
	if _, ok := raw["echo"]; raw != nil && !ok {
		return fmt.Errorf("field echo in RootOneOfDiscriminatorPong: required")
	}
	if _, ok := raw["kind"]; raw != nil && !ok {
		return fmt.Errorf("field kind in RootOneOfDiscriminatorPong: required")
	}
	type Plain RootOneOfDiscriminatorPong
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return fmt.Errorf("unmarshal RootOneOfDiscriminatorPong: %w", err)
	}
	if plain.Kind != "pong" {
		return fmt.Errorf("field %s: must be equal to %s", "kind", "pong")
	}
	*j = RootOneOfDiscriminatorPong(plain)
	return nil
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *RootOneOfDiscriminatorPong) UnmarshalYAML(value *yaml.Node) error {
	var raw map[string]interface{}
	if err := value.Decode(&raw); err != nil {
		return fmt.Errorf("unmarshal raw RootOneOfDiscriminatorPong: %w", err)
	}
	if _, ok := raw["echo"]; raw != nil && !ok {
		return fmt.Errorf("field echo in RootOneOfDiscriminatorPong: required")
	}
	if _, ok := raw["kind"]; raw != nil && !ok {
		return fmt.Errorf("field kind in RootOneOfDiscriminatorPong: required")
	}
	type Plain RootOneOfDiscriminatorPong
	var plain Plain
	if err := value.Decode(&plain); err != nil {
		return fmt.Errorf("unmarshal RootOneOfDiscriminatorPong: %w", err)
	}
	if plain.Kind != "pong" {
		return fmt.Errorf("field %s: must be equal to %s", "kind", "pong")
	}
	*j = RootOneOfDiscriminatorPong(plain)
	return nil
}

// MarshalJSON implements json.Marshaler. Exactly one variant
// pointer must be non-nil; otherwise marshaling errors.
func (j RootOneOfDiscriminator) MarshalJSON() ([]byte, error) {
	set := 0
	if j.Ping != nil {
		set++
	}
	if j.Pong != nil {
		set++
	}
	if set != 1 {
		return nil, fmt.Errorf("RootOneOfDiscriminator: exactly one variant must be set, got %d", set)
	}
	if j.Ping != nil {
		return json.Marshal(j.Ping)
	}
	if j.Pong != nil {
		return json.Marshal(j.Pong)
	}
	return nil, nil // unreachable
}

// MarshalYAML mirrors MarshalJSON.
func (j RootOneOfDiscriminator) MarshalYAML() (interface{}, error) {
	set := 0
	if j.Ping != nil {
		set++
	}
	if j.Pong != nil {
		set++
	}
	if set != 1 {
		return nil, fmt.Errorf("RootOneOfDiscriminator: exactly one variant must be set, got %d", set)
	}
	if j.Ping != nil {
		return j.Ping, nil
	}
	if j.Pong != nil {
		return j.Pong, nil
	}
	return nil, nil // unreachable
}

// UnmarshalJSON implements json.Unmarshaler. It peeks the
// discriminator property "kind" and dispatches the decode into the
// matching variant.
func (j *RootOneOfDiscriminator) UnmarshalJSON(value []byte) error {
	// Reset to zero value so reusing the same holder across multiple
	// Unmarshal calls doesn't leave a previous winner set alongside the
	// new one (which would violate the one-variant-set invariant and
	// break the corresponding MarshalJSON).
	*j = RootOneOfDiscriminator{}
	var peek struct {
		Discriminator json.RawMessage `json:"kind"`
	}
	if err := json.Unmarshal(value, &peek); err != nil {
		return fmt.Errorf("unmarshal RootOneOfDiscriminator: %w", err)
	}
	if len(peek.Discriminator) == 0 {
		return fmt.Errorf("RootOneOfDiscriminator: missing discriminator field kind")
	}
	switch string(peek.Discriminator) {
	case "\"ping\"":
		var v RootOneOfDiscriminatorPing
		if err := json.Unmarshal(value, &v); err != nil {
			return fmt.Errorf("RootOneOfDiscriminator.Ping: %w", err)
		}
		j.Ping = &v
	case "\"pong\"":
		var v RootOneOfDiscriminatorPong
		if err := json.Unmarshal(value, &v); err != nil {
			return fmt.Errorf("RootOneOfDiscriminator.Pong: %w", err)
		}
		j.Pong = &v
	default:
		return fmt.Errorf("RootOneOfDiscriminator: unknown kind value %s", string(peek.Discriminator))
	}
	return nil
}

// UnmarshalYAML mirrors UnmarshalJSON: peek the discriminator
// then dispatch to the matching variant.
func (j *RootOneOfDiscriminator) UnmarshalYAML(value *yaml.Node) error {
	// Reset to zero value so reusing the same holder across multiple
	// Unmarshal calls doesn't leave a previous winner set alongside the
	// new one (which would violate the one-variant-set invariant and
	// break the corresponding MarshalYAML).
	*j = RootOneOfDiscriminator{}
	var peek struct {
		Discriminator yaml.Node `yaml:"kind"`
	}
	if err := value.Decode(&peek); err != nil {
		return fmt.Errorf("unmarshal RootOneOfDiscriminator: %w", err)
	}
	if peek.Discriminator.Kind == 0 {
		return fmt.Errorf("RootOneOfDiscriminator: missing discriminator field kind")
	}
	switch peek.Discriminator.Value {
	case "ping":
		var v RootOneOfDiscriminatorPing
		if err := value.Decode(&v); err != nil {
			return fmt.Errorf("RootOneOfDiscriminator.Ping: %w", err)
		}
		j.Ping = &v
	case "pong":
		var v RootOneOfDiscriminatorPong
		if err := value.Decode(&v); err != nil {
			return fmt.Errorf("RootOneOfDiscriminator.Pong: %w", err)
		}
		j.Pong = &v
	default:
		return fmt.Errorf("RootOneOfDiscriminator: unknown kind value %q", peek.Discriminator.Value)
	}
	return nil
}
