// Code generated by github.com/tuotuoxp/go-jsonschema, DO NOT EDIT.

package test

import shared "github.com/tuotuoxp/go-jsonschema/tests/helpers/shared"

type PlainUser struct {
	// Id corresponds to the JSON schema field "id".
	Id *string `json:"id,omitempty,omitzero" yaml:"id,omitempty" mapstructure:"id,omitempty"`
}

type RefXGoImport struct {
	// PlainUser corresponds to the JSON schema field "plainUser".
	PlainUser *PlainUser `json:"plainUser,omitempty,omitzero" yaml:"plainUser,omitempty" mapstructure:"plainUser,omitempty"`

	// SharedUser corresponds to the JSON schema field "sharedUser".
	SharedUser *shared.User `json:"sharedUser,omitempty,omitzero" yaml:"sharedUser,omitempty" mapstructure:"sharedUser,omitempty"`
}
