// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package test

import "encoding/json"
import "fmt"
import yaml "gopkg.in/yaml.v3"
import "reflect"

type RootConstEnum string

const RootConstEnumFixed RootConstEnum = "fixed"

var enumValues_RootConstEnum = []interface{}{
	"fixed",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *RootConstEnum) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_RootConstEnum {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_RootConstEnum, v)
	}
	*j = RootConstEnum(v)
	return nil
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *RootConstEnum) UnmarshalYAML(value *yaml.Node) error {
	var v string
	if err := value.Decode(&v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_RootConstEnum {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_RootConstEnum, v)
	}
	*j = RootConstEnum(v)
	return nil
}
