// Code generated by github.com/tuotuoxp/go-jsonschema, DO NOT EDIT.

package test

type YamlStructNameFromFile struct {
	// Foo corresponds to the JSON schema field "foo".
	Foo *string `json:"foo,omitempty,omitzero" yaml:"foo,omitempty" mapstructure:"foo,omitempty"`
}
