// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package test

import "encoding/json"
import "fmt"
import yaml "gopkg.in/yaml.v3"

type ArrayParentItems struct {
	// The array holding the oneOf declares its own element schema. A holder would
	// replace the field that checks it, so the typed array stays.
	List []ArrayParentItemsListElem `json:"list,omitempty,omitzero" yaml:"list,omitempty" mapstructure:"list,omitempty"`
}

type ArrayParentItemsListElem struct {
	// Id corresponds to the JSON schema field "id".
	Id string `json:"id" yaml:"id" mapstructure:"id"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ArrayParentItemsListElem) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return fmt.Errorf("unmarshal raw ArrayParentItemsListElem: %w", err)
	}
	if _, ok := raw["id"]; raw != nil && !ok {
		return fmt.Errorf("field id in ArrayParentItemsListElem: required")
	}
	type Plain ArrayParentItemsListElem
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return fmt.Errorf("unmarshal ArrayParentItemsListElem: %w", err)
	}
	*j = ArrayParentItemsListElem(plain)
	return nil
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *ArrayParentItemsListElem) UnmarshalYAML(value *yaml.Node) error {
	var raw map[string]interface{}
	if err := value.Decode(&raw); err != nil {
		return fmt.Errorf("unmarshal raw ArrayParentItemsListElem: %w", err)
	}
	if _, ok := raw["id"]; raw != nil && !ok {
		return fmt.Errorf("field id in ArrayParentItemsListElem: required")
	}
	type Plain ArrayParentItemsListElem
	var plain Plain
	if err := value.Decode(&plain); err != nil {
		return fmt.Errorf("unmarshal ArrayParentItemsListElem: %w", err)
	}
	*j = ArrayParentItemsListElem(plain)
	return nil
}
