// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package test

import "bytes"
import "encoding/json"
import "fmt"
import yaml "gopkg.in/yaml.v3"
import "time"

type TemporalVariant struct {
	// A non-temporal constraint still disqualifies the wrapper, and the fidelity
	// warning still reports it.
	StillRejected interface{} `json:"stillRejected,omitempty,omitzero" yaml:"stillRejected,omitempty" mapstructure:"stillRejected,omitempty"`

	// The shape CycloneDX-style trend axes use: a value that is either an RFC3339
	// timestamp or a number. Before temporal support the format disqualified the
	// variant and the whole field degraded to interface{}.
	TimeOrNumber *TemporalVariantTimeOrNumber `json:"timeOrNumber,omitempty,omitzero" yaml:"timeOrNumber,omitempty" mapstructure:"timeOrNumber,omitempty"`
}

// The shape CycloneDX-style trend axes use: a value that is either an RFC3339
// timestamp or a number. Before temporal support the format disqualified the
// variant and the whole field degraded to interface{}.
type TemporalVariantTimeOrNumber struct {
	value interface{}

	present bool
}

// AsDateTime returns the value as a time.Time and reports whether it was a
// date-time.
func (j *TemporalVariantTimeOrNumber) AsDateTime() (time.Time, bool) {
	if j == nil || !j.present {
		return time.Time{}, false
	}
	v, ok := j.value.(time.Time)
	return v, ok
}

// AsNumber returns the value as a float64 and reports whether it was numeric.
func (j *TemporalVariantTimeOrNumber) AsNumber() (float64, bool) {
	if j == nil || !j.present {
		return 0, false
	}
	v, ok := j.value.(float64)
	return v, ok
}

// IsZero reports whether the wrapper has not been populated by
// Unmarshal{JSON,YAML}; supports the encoding/json `omitzero` tag. Note: an
// explicitly-decoded JSON `null` is NOT zero — see IsNull.
func (j *TemporalVariantTimeOrNumber) IsZero() bool {
	return j == nil || !j.present
}

// MarshalJSON implements json.Marshaler.
func (j *TemporalVariantTimeOrNumber) MarshalJSON() ([]byte, error) {
	if j == nil || !j.present {
		return nil, fmt.Errorf("TemporalVariantTimeOrNumber: cannot marshal unset value (schema does not allow null)")
	}
	if j.value == nil {
		return nil, fmt.Errorf("TemporalVariantTimeOrNumber: cannot marshal nil value (schema does not allow null)")
	}
	return json.Marshal(j.value)
}

// MarshalYAML implements yaml.Marshaler.
func (j *TemporalVariantTimeOrNumber) MarshalYAML() (interface{}, error) {
	if j == nil || !j.present {
		return nil, fmt.Errorf("TemporalVariantTimeOrNumber: cannot marshal unset value (schema does not allow null)")
	}
	if j.value == nil {
		return nil, fmt.Errorf("TemporalVariantTimeOrNumber: cannot marshal nil value (schema does not allow null)")
	}
	return j.value, nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *TemporalVariantTimeOrNumber) UnmarshalJSON(value []byte) error {
	dec := json.NewDecoder(bytes.NewReader(value))
	dec.UseNumber()
	tok, err := dec.Token()
	if err != nil {
		return err
	}
	switch tok.(type) {
	case string:
		var v time.Time
		if err := json.Unmarshal(value, &v); err != nil {
			return err
		}
		j.value = v
	case json.Number:
		var v float64
		if err := json.Unmarshal(value, &v); err != nil {
			return err
		}
		j.value = v
	default:
		return fmt.Errorf("TemporalVariantTimeOrNumber: unsupported JSON value of type %T", tok)
	}
	j.present = true
	return nil
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *TemporalVariantTimeOrNumber) UnmarshalYAML(value *yaml.Node) error {
	if value.Kind != yaml.ScalarNode {
		return fmt.Errorf("TemporalVariantTimeOrNumber: expected scalar YAML node")
	}
	switch value.Tag {
	case "!!str":
		var v time.Time
		if err := value.Decode(&v); err != nil {
			return err
		}
		j.value = v
	case "!!int", "!!float":
		var v float64
		if err := value.Decode(&v); err != nil {
			return err
		}
		j.value = v
	default:
		return fmt.Errorf("TemporalVariantTimeOrNumber: unsupported YAML scalar tag %q", value.Tag)
	}
	j.present = true
	return nil
}

// Value returns the decoded primitive payload.
func (j *TemporalVariantTimeOrNumber) Value() any {
	if j == nil {
		return nil
	}
	return j.value
}
