// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package test

import "encoding/json"
import "fmt"
import yaml "gopkg.in/yaml.v3"

type CaseCollision struct {
	// "dog" and "Dog" are distinct discriminator values that map to one Go
	// identifier, so the second variant's holder field is suffixed; without that the
	// holder declared Dog twice and did not compile.
	Pet *CaseCollisionPet `json:"pet,omitempty,omitzero" yaml:"pet,omitempty" mapstructure:"pet,omitempty"`
}

// "dog" and "Dog" are distinct discriminator values that map to one Go identifier,
// so the second variant's holder field is suffixed; without that the holder
// declared Dog twice and did not compile.
type CaseCollisionPet struct {
	Dog *CaseCollisionPetDog `json:"-" yaml:"-"`

	Dog_2 *CaseCollisionPetDog_2 `json:"-" yaml:"-"`
}

type CaseCollisionPetDog struct {
	// Bark corresponds to the JSON schema field "bark".
	Bark *string `json:"bark,omitempty,omitzero" yaml:"bark,omitempty" mapstructure:"bark,omitempty"`

	// Kind corresponds to the JSON schema field "kind".
	Kind interface{} `json:"kind" yaml:"kind" mapstructure:"kind"`
}

type CaseCollisionPetDog_2 struct {
	// Howl corresponds to the JSON schema field "howl".
	Howl *string `json:"howl,omitempty,omitzero" yaml:"howl,omitempty" mapstructure:"howl,omitempty"`

	// Kind corresponds to the JSON schema field "kind".
	Kind interface{} `json:"kind" yaml:"kind" mapstructure:"kind"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *CaseCollisionPetDog_2) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return fmt.Errorf("unmarshal raw CaseCollisionPetDog_2: %w", err)
	}
	if _, ok := raw["kind"]; raw != nil && !ok {
		return fmt.Errorf("field kind in CaseCollisionPetDog_2: required")
	}
	type Plain CaseCollisionPetDog_2
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return fmt.Errorf("unmarshal CaseCollisionPetDog_2: %w", err)
	}
	*j = CaseCollisionPetDog_2(plain)
	return nil
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *CaseCollisionPetDog_2) UnmarshalYAML(value *yaml.Node) error {
	var raw map[string]interface{}
	if err := value.Decode(&raw); err != nil {
		return fmt.Errorf("unmarshal raw CaseCollisionPetDog_2: %w", err)
	}
	if _, ok := raw["kind"]; raw != nil && !ok {
		return fmt.Errorf("field kind in CaseCollisionPetDog_2: required")
	}
	type Plain CaseCollisionPetDog_2
	var plain Plain
	if err := value.Decode(&plain); err != nil {
		return fmt.Errorf("unmarshal CaseCollisionPetDog_2: %w", err)
	}
	*j = CaseCollisionPetDog_2(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *CaseCollisionPetDog) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return fmt.Errorf("unmarshal raw CaseCollisionPetDog: %w", err)
	}
	if _, ok := raw["kind"]; raw != nil && !ok {
		return fmt.Errorf("field kind in CaseCollisionPetDog: required")
	}
	type Plain CaseCollisionPetDog
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return fmt.Errorf("unmarshal CaseCollisionPetDog: %w", err)
	}
	*j = CaseCollisionPetDog(plain)
	return nil
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *CaseCollisionPetDog) UnmarshalYAML(value *yaml.Node) error {
	var raw map[string]interface{}
	if err := value.Decode(&raw); err != nil {
		return fmt.Errorf("unmarshal raw CaseCollisionPetDog: %w", err)
	}
	if _, ok := raw["kind"]; raw != nil && !ok {
		return fmt.Errorf("field kind in CaseCollisionPetDog: required")
	}
	type Plain CaseCollisionPetDog
	var plain Plain
	if err := value.Decode(&plain); err != nil {
		return fmt.Errorf("unmarshal CaseCollisionPetDog: %w", err)
	}
	*j = CaseCollisionPetDog(plain)
	return nil
}

// MarshalJSON implements json.Marshaler. Exactly one variant
// pointer must be non-nil; otherwise marshaling errors.
func (j CaseCollisionPet) MarshalJSON() ([]byte, error) {
	set := 0
	if j.Dog != nil {
		set++
	}
	if j.Dog_2 != nil {
		set++
	}
	if set != 1 {
		return nil, fmt.Errorf("CaseCollisionPet: exactly one variant must be set, got %d", set)
	}
	if j.Dog != nil {
		return json.Marshal(j.Dog)
	}
	if j.Dog_2 != nil {
		return json.Marshal(j.Dog_2)
	}
	return nil, nil // unreachable
}

// MarshalYAML mirrors MarshalJSON.
func (j CaseCollisionPet) MarshalYAML() (interface{}, error) {
	set := 0
	if j.Dog != nil {
		set++
	}
	if j.Dog_2 != nil {
		set++
	}
	if set != 1 {
		return nil, fmt.Errorf("CaseCollisionPet: exactly one variant must be set, got %d", set)
	}
	if j.Dog != nil {
		return j.Dog, nil
	}
	if j.Dog_2 != nil {
		return j.Dog_2, nil
	}
	return nil, nil // unreachable
}

// UnmarshalJSON implements json.Unmarshaler. It peeks the
// discriminator property "kind" and dispatches the decode into the
// matching variant.
func (j *CaseCollisionPet) UnmarshalJSON(value []byte) error {
	// Reset to zero value so reusing the same holder across multiple
	// Unmarshal calls doesn't leave a previous winner set alongside the
	// new one (which would violate the one-variant-set invariant and
	// break the corresponding MarshalJSON).
	*j = CaseCollisionPet{}
	var peek struct {
		Discriminator json.RawMessage `json:"kind"`
	}
	if err := json.Unmarshal(value, &peek); err != nil {
		return fmt.Errorf("unmarshal CaseCollisionPet: %w", err)
	}
	if len(peek.Discriminator) == 0 {
		return fmt.Errorf("CaseCollisionPet: missing discriminator field kind")
	}
	if string(peek.Discriminator) == "null" {
		return fmt.Errorf("CaseCollisionPet: kind discriminator must be a string, got null")
	}
	var disc string
	if err := json.Unmarshal(peek.Discriminator, &disc); err != nil {
		return fmt.Errorf("CaseCollisionPet: kind discriminator must be a string: %w", err)
	}
	switch disc {
	case "dog":
		var v CaseCollisionPetDog
		if err := json.Unmarshal(value, &v); err != nil {
			return fmt.Errorf("CaseCollisionPet.Dog: %w", err)
		}
		j.Dog = &v
	case "Dog":
		var v CaseCollisionPetDog_2
		if err := json.Unmarshal(value, &v); err != nil {
			return fmt.Errorf("CaseCollisionPet.Dog_2: %w", err)
		}
		j.Dog_2 = &v
	default:
		return fmt.Errorf("CaseCollisionPet: unknown kind value %q", disc)
	}
	return nil
}

// UnmarshalYAML mirrors UnmarshalJSON: peek the discriminator
// then dispatch to the matching variant.
func (j *CaseCollisionPet) UnmarshalYAML(value *yaml.Node) error {
	// Reset to zero value so reusing the same holder across multiple
	// Unmarshal calls doesn't leave a previous winner set alongside the
	// new one (which would violate the one-variant-set invariant and
	// break the corresponding MarshalYAML).
	*j = CaseCollisionPet{}
	var peek struct {
		Discriminator yaml.Node `yaml:"kind"`
	}
	if err := value.Decode(&peek); err != nil {
		return fmt.Errorf("unmarshal CaseCollisionPet: %w", err)
	}
	if peek.Discriminator.Kind == 0 {
		return fmt.Errorf("CaseCollisionPet: missing discriminator field kind")
	}
	switch peek.Discriminator.Value {
	case "dog":
		var v CaseCollisionPetDog
		if err := value.Decode(&v); err != nil {
			return fmt.Errorf("CaseCollisionPet.Dog: %w", err)
		}
		j.Dog = &v
	case "Dog":
		var v CaseCollisionPetDog_2
		if err := value.Decode(&v); err != nil {
			return fmt.Errorf("CaseCollisionPet.Dog_2: %w", err)
		}
		j.Dog_2 = &v
	default:
		return fmt.Errorf("CaseCollisionPet: unknown kind value %q", peek.Discriminator.Value)
	}
	return nil
}
