// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package test

import "encoding/json"
import "fmt"
import yaml "gopkg.in/yaml.v3"
import "reflect"

type Duplicate string

const DuplicateTwo Duplicate = "two"

var enumValues_Duplicate = []interface{}{
	"one",
	"two",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Duplicate) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_Duplicate {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_Duplicate, v)
	}
	*j = Duplicate(v)
	return nil
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *Duplicate) UnmarshalYAML(value *yaml.Node) error {
	var v string
	if err := value.Decode(&v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_Duplicate {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_Duplicate, v)
	}
	*j = Duplicate(v)
	return nil
}

type EnumVarnamesInvalid struct {
	// Duplicate corresponds to the JSON schema field "duplicate".
	Duplicate *Duplicate `json:"duplicate,omitempty,omitzero" yaml:"duplicate,omitempty" mapstructure:"duplicate,omitempty"`

	// Mismatch corresponds to the JSON schema field "mismatch".
	Mismatch *Mismatch `json:"mismatch,omitempty,omitzero" yaml:"mismatch,omitempty" mapstructure:"mismatch,omitempty"`

	// NotAnIdentifier corresponds to the JSON schema field "notAnIdentifier".
	NotAnIdentifier *NotAnIdentifier `json:"notAnIdentifier,omitempty,omitzero" yaml:"notAnIdentifier,omitempty" mapstructure:"notAnIdentifier,omitempty"`

	// SelfNamed corresponds to the JSON schema field "selfNamed".
	SelfNamed *SelfNamed `json:"selfNamed,omitempty,omitzero" yaml:"selfNamed,omitempty" mapstructure:"selfNamed,omitempty"`
}

const Fine SelfNamed = "y"
const KebabCaseName NotAnIdentifier = "x"

type Mismatch string

const MismatchAlpha Mismatch = "alpha"
const MismatchBeta Mismatch = "beta"

var enumValues_Mismatch = []interface{}{
	"alpha",
	"beta",
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *Mismatch) UnmarshalYAML(value *yaml.Node) error {
	var v string
	if err := value.Decode(&v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_Mismatch {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_Mismatch, v)
	}
	*j = Mismatch(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Mismatch) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_Mismatch {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_Mismatch, v)
	}
	*j = Mismatch(v)
	return nil
}

type NotAnIdentifier string

const NotAnIdentifierY NotAnIdentifier = "y"

var enumValues_NotAnIdentifier = []interface{}{
	"x",
	"y",
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *NotAnIdentifier) UnmarshalYAML(value *yaml.Node) error {
	var v string
	if err := value.Decode(&v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_NotAnIdentifier {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_NotAnIdentifier, v)
	}
	*j = NotAnIdentifier(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *NotAnIdentifier) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_NotAnIdentifier {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_NotAnIdentifier, v)
	}
	*j = NotAnIdentifier(v)
	return nil
}

const Same Duplicate = "one"

type SelfNamed string

const SelfNamedX SelfNamed = "x"

var enumValues_SelfNamed = []interface{}{
	"x",
	"y",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *SelfNamed) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_SelfNamed {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_SelfNamed, v)
	}
	*j = SelfNamed(v)
	return nil
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *SelfNamed) UnmarshalYAML(value *yaml.Node) error {
	var v string
	if err := value.Decode(&v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_SelfNamed {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_SelfNamed, v)
	}
	*j = SelfNamed(v)
	return nil
}
