// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package test

import "encoding/json"
import "fmt"
import yaml "gopkg.in/yaml.v3"
import "reflect"

type EnumVarnamesCrossEnum struct {
	// First corresponds to the JSON schema field "first".
	First *XcFirst `json:"first,omitempty,omitzero" yaml:"first,omitempty" mapstructure:"first,omitempty"`

	// Second corresponds to the JSON schema field "second".
	Second *XcSecond `json:"second,omitempty,omitzero" yaml:"second,omitempty" mapstructure:"second,omitempty"`
}

type XcFirst string

const XcFirstOther XcFirst = "q"

var enumValues_XcFirst = []interface{}{
	"p",
	"q",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *XcFirst) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_XcFirst {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_XcFirst, v)
	}
	*j = XcFirst(v)
	return nil
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *XcFirst) UnmarshalYAML(value *yaml.Node) error {
	var v string
	if err := value.Decode(&v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_XcFirst {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_XcFirst, v)
	}
	*j = XcFirst(v)
	return nil
}

type XcSecond string

const XcSecondX XcFirst = "p"
const XcSecondX_1 XcSecond = "x"
const XcSecondY XcSecond = "y"

var enumValues_XcSecond = []interface{}{
	"x",
	"y",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *XcSecond) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_XcSecond {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_XcSecond, v)
	}
	*j = XcSecond(v)
	return nil
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *XcSecond) UnmarshalYAML(value *yaml.Node) error {
	var v string
	if err := value.Decode(&v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_XcSecond {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_XcSecond, v)
	}
	*j = XcSecond(v)
	return nil
}
