// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package test

import "encoding/json"
import "fmt"
import yaml "gopkg.in/yaml.v3"
import "reflect"

const Completed JobStatus = "completed"
const Created JobStatus = "created"
const CustomAlpha Partial = "alpha"

type EnumVarnames struct {
	// Partial corresponds to the JSON schema field "partial".
	Partial *Partial `json:"partial,omitempty,omitzero" yaml:"partial,omitempty" mapstructure:"partial,omitempty"`

	// Priority corresponds to the JSON schema field "priority".
	Priority *NoExtension `json:"priority,omitempty,omitzero" yaml:"priority,omitempty" mapstructure:"priority,omitempty"`

	// Running corresponds to the JSON schema field "running".
	Running *RunningStatus `json:"running,omitempty,omitzero" yaml:"running,omitempty" mapstructure:"running,omitempty"`

	// Status corresponds to the JSON schema field "status".
	Status *JobStatus `json:"status,omitempty,omitzero" yaml:"status,omitempty" mapstructure:"status,omitempty"`

	// Underscored corresponds to the JSON schema field "underscored".
	Underscored *Underscored `json:"underscored,omitempty,omitzero" yaml:"underscored,omitempty" mapstructure:"underscored,omitempty"`
}

const HTTP_Status Underscored = "a"

type JobStatus string

var enumValues_JobStatus = []interface{}{
	"created",
	"queued",
	"running",
	"completed",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *JobStatus) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_JobStatus {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_JobStatus, v)
	}
	*j = JobStatus(v)
	return nil
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *JobStatus) UnmarshalYAML(value *yaml.Node) error {
	var v string
	if err := value.Decode(&v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_JobStatus {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_JobStatus, v)
	}
	*j = JobStatus(v)
	return nil
}

type NoExtension string

const NoExtensionBatch NoExtension = "Batch"
const NoExtensionOnDemand NoExtension = "OnDemand"

var enumValues_NoExtension = []interface{}{
	"OnDemand",
	"Batch",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *NoExtension) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_NoExtension {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_NoExtension, v)
	}
	*j = NoExtension(v)
	return nil
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *NoExtension) UnmarshalYAML(value *yaml.Node) error {
	var v string
	if err := value.Decode(&v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_NoExtension {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_NoExtension, v)
	}
	*j = NoExtension(v)
	return nil
}

const OK_Response Underscored = "b"

type Partial string

const PartialBeta Partial = "beta"

var enumValues_Partial = []interface{}{
	"alpha",
	"beta",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Partial) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_Partial {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_Partial, v)
	}
	*j = Partial(v)
	return nil
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *Partial) UnmarshalYAML(value *yaml.Node) error {
	var v string
	if err := value.Decode(&v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_Partial {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_Partial, v)
	}
	*j = Partial(v)
	return nil
}

const Queued JobStatus = "queued"
const Running JobStatus = "running"

type RunningStatus string

const RunningStatusCancelling RunningStatus = "cancelling"
const RunningStatusRunning RunningStatus = "running"

var enumValues_RunningStatus = []interface{}{
	"running",
	"cancelling",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *RunningStatus) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_RunningStatus {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_RunningStatus, v)
	}
	*j = RunningStatus(v)
	return nil
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *RunningStatus) UnmarshalYAML(value *yaml.Node) error {
	var v string
	if err := value.Decode(&v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_RunningStatus {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_RunningStatus, v)
	}
	*j = RunningStatus(v)
	return nil
}

type Underscored string

var enumValues_Underscored = []interface{}{
	"a",
	"b",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Underscored) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_Underscored {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_Underscored, v)
	}
	*j = Underscored(v)
	return nil
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *Underscored) UnmarshalYAML(value *yaml.Node) error {
	var v string
	if err := value.Decode(&v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_Underscored {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_Underscored, v)
	}
	*j = Underscored(v)
	return nil
}
