// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package test

import "encoding/json"
import "fmt"
import yaml "gopkg.in/yaml.v3"
import "regexp"

type Uuid struct {
	// Id corresponds to the JSON schema field "id".
	Id string `json:"id" yaml:"id" mapstructure:"id"`

	// ParentId corresponds to the JSON schema field "parentId".
	ParentId *string `json:"parentId,omitempty,omitzero" yaml:"parentId,omitempty" mapstructure:"parentId,omitempty"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Uuid) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return fmt.Errorf("unmarshal raw Uuid: %w", err)
	}
	if _, ok := raw["id"]; raw != nil && !ok {
		return fmt.Errorf("field id in Uuid: required")
	}
	type Plain Uuid
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return fmt.Errorf("unmarshal Uuid: %w", err)
	}
	if !regexpFormatUUID.MatchString(string(plain.Id)) {
		return fmt.Errorf("field %s: must be a valid uuid", "id")
	}
	if plain.ParentId != nil {
		if !regexpFormatUUID.MatchString(string(*plain.ParentId)) {
			return fmt.Errorf("field %s: must be a valid uuid", "parentId")
		}
	}
	*j = Uuid(plain)
	return nil
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *Uuid) UnmarshalYAML(value *yaml.Node) error {
	var raw map[string]interface{}
	if err := value.Decode(&raw); err != nil {
		return fmt.Errorf("unmarshal raw Uuid: %w", err)
	}
	if _, ok := raw["id"]; raw != nil && !ok {
		return fmt.Errorf("field id in Uuid: required")
	}
	type Plain Uuid
	var plain Plain
	if err := value.Decode(&plain); err != nil {
		return fmt.Errorf("unmarshal Uuid: %w", err)
	}
	if !regexpFormatUUID.MatchString(string(plain.Id)) {
		return fmt.Errorf("field %s: must be a valid uuid", "id")
	}
	if plain.ParentId != nil {
		if !regexpFormatUUID.MatchString(string(*plain.ParentId)) {
			return fmt.Errorf("field %s: must be a valid uuid", "parentId")
		}
	}
	*j = Uuid(plain)
	return nil
}

var regexpFormatUUID = regexp.MustCompile(`^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$`)
