// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package test

import "encoding/json"
import "fmt"
import yaml "gopkg.in/yaml.v3"
import "net/netip"

type IpDefault struct {
	// Ipv4 corresponds to the JSON schema field "ipv4".
	Ipv4 netip.Addr `json:"ipv4,omitempty,omitzero" yaml:"ipv4,omitempty" mapstructure:"ipv4,omitempty"`

	// Ipv6 corresponds to the JSON schema field "ipv6".
	Ipv6 netip.Addr `json:"ipv6,omitempty,omitzero" yaml:"ipv6,omitempty" mapstructure:"ipv6,omitempty"`

	// NullableIpv4 corresponds to the JSON schema field "nullableIpv4".
	NullableIpv4 *netip.Addr `json:"nullableIpv4,omitempty,omitzero" yaml:"nullableIpv4,omitempty" mapstructure:"nullableIpv4,omitempty"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *IpDefault) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	type Plain IpDefault
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if v, ok := raw["ipv4"]; !ok || v == nil {
		defaultIP, err := netip.ParseAddr("127.0.0.1")
		if err != nil {
			return fmt.Errorf("failed to parse the \"127.0.0.1\" default value for field ipv4: %w", err)
		}
		plain.Ipv4 = defaultIP

	}
	if v, ok := raw["ipv6"]; !ok || v == nil {
		defaultIP, err := netip.ParseAddr("2001:db8::68")
		if err != nil {
			return fmt.Errorf("failed to parse the \"2001:db8::68\" default value for field ipv6: %w", err)
		}
		plain.Ipv6 = defaultIP

	}
	if v, ok := raw["nullableIpv4"]; !ok || v == nil {
		defaultIP, err := netip.ParseAddr("192.168.1.1")
		if err != nil {
			return fmt.Errorf("failed to parse the \"192.168.1.1\" default value for field nullableIpv4: %w", err)
		}
		plain.NullableIpv4 = &defaultIP

	}
	*j = IpDefault(plain)
	return nil
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *IpDefault) UnmarshalYAML(value *yaml.Node) error {
	var raw map[string]interface{}
	if err := value.Decode(&raw); err != nil {
		return err
	}
	type Plain IpDefault
	var plain Plain
	if err := value.Decode(&plain); err != nil {
		return err
	}
	if v, ok := raw["ipv4"]; !ok || v == nil {
		defaultIP, err := netip.ParseAddr("127.0.0.1")
		if err != nil {
			return fmt.Errorf("failed to parse the \"127.0.0.1\" default value for field ipv4: %w", err)
		}
		plain.Ipv4 = defaultIP

	}
	if v, ok := raw["ipv6"]; !ok || v == nil {
		defaultIP, err := netip.ParseAddr("2001:db8::68")
		if err != nil {
			return fmt.Errorf("failed to parse the \"2001:db8::68\" default value for field ipv6: %w", err)
		}
		plain.Ipv6 = defaultIP

	}
	if v, ok := raw["nullableIpv4"]; !ok || v == nil {
		defaultIP, err := netip.ParseAddr("192.168.1.1")
		if err != nil {
			return fmt.Errorf("failed to parse the \"192.168.1.1\" default value for field nullableIpv4: %w", err)
		}
		plain.NullableIpv4 = &defaultIP

	}
	*j = IpDefault(plain)
	return nil
}
