// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package test

import "encoding/json"
import "fmt"
import yaml "gopkg.in/yaml.v3"

type NullAllowed struct {
	// Nullable corresponds to the JSON schema field "nullable".
	Nullable NullAllowedNullable `json:"nullable,omitempty,omitzero" yaml:"nullable,omitempty" mapstructure:"nullable,omitempty"`

	// Strict corresponds to the JSON schema field "strict".
	Strict *string `json:"strict,omitempty,omitzero" yaml:"strict,omitempty" mapstructure:"strict,omitempty"`

	// no type keyword at all
	Untyped interface{} `json:"untyped,omitempty,omitzero" yaml:"untyped,omitempty" mapstructure:"untyped,omitempty"`
}

type NullAllowedNullable *string

// UnmarshalJSON implements json.Unmarshaler.
func (j *NullAllowed) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return fmt.Errorf("unmarshal raw NullAllowed: %w", err)
	}
	if raw == nil {
		return fmt.Errorf("NullAllowed: must not be null")
	}
	if fieldValue, ok := raw["strict"]; ok && fieldValue == nil {
		return fmt.Errorf("field strict in NullAllowed: must not be null")
	}
	type Plain NullAllowed
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = NullAllowed(plain)
	return nil
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *NullAllowed) UnmarshalYAML(value *yaml.Node) error {
	var raw map[string]interface{}
	if err := value.Decode(&raw); err != nil {
		return fmt.Errorf("unmarshal raw NullAllowed: %w", err)
	}
	if raw == nil {
		return fmt.Errorf("NullAllowed: must not be null")
	}
	if fieldValue, ok := raw["strict"]; ok && fieldValue == nil {
		return fmt.Errorf("field strict in NullAllowed: must not be null")
	}
	type Plain NullAllowed
	var plain Plain
	if err := value.Decode(&plain); err != nil {
		return err
	}
	*j = NullAllowed(plain)
	return nil
}
