// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package test

import "encoding/json"
import "fmt"
import yaml "gopkg.in/yaml.v3"
import "sort"

type AddlFalseEmpty struct {
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *AddlFalseEmpty) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return fmt.Errorf("unmarshal raw AddlFalseEmpty: %w", err)
	}
	if raw != nil {
		var extraKeys []string
		for additionalKey := range raw {
			switch additionalKey {
			default:
				extraKeys = append(extraKeys, additionalKey)
			}
		}
		if len(extraKeys) > 0 {
			sort.Strings(extraKeys)
			return fmt.Errorf("fields %q in AddlFalseEmpty: additional properties not allowed", extraKeys)
		}
	}
	type Plain AddlFalseEmpty
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return fmt.Errorf("unmarshal AddlFalseEmpty: %w", err)
	}
	*j = AddlFalseEmpty(plain)
	return nil
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *AddlFalseEmpty) UnmarshalYAML(value *yaml.Node) error {
	var raw map[string]interface{}
	if err := value.Decode(&raw); err != nil {
		return fmt.Errorf("unmarshal raw AddlFalseEmpty: %w", err)
	}
	if raw != nil {
		var extraKeys []string
		for additionalKey := range raw {
			switch additionalKey {
			default:
				extraKeys = append(extraKeys, additionalKey)
			}
		}
		if len(extraKeys) > 0 {
			sort.Strings(extraKeys)
			return fmt.Errorf("fields %q in AddlFalseEmpty: additional properties not allowed", extraKeys)
		}
	}
	type Plain AddlFalseEmpty
	var plain Plain
	if err := value.Decode(&plain); err != nil {
		return fmt.Errorf("unmarshal AddlFalseEmpty: %w", err)
	}
	*j = AddlFalseEmpty(plain)
	return nil
}
