// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package test

import "encoding/json"
import "errors"
import "fmt"
import yaml "gopkg.in/yaml.v3"

// object with anyOf properties, some with $defs
type AnyOf2 struct {
	// Configurations corresponds to the JSON schema field "configurations".
	Configurations []AnyOf2ConfigurationsElem `json:"configurations,omitempty" yaml:"configurations,omitempty" mapstructure:"configurations,omitempty"`
}

type AnyOf2ConfigurationsElem struct {
	// Bar corresponds to the JSON schema field "bar".
	Bar *float64 `json:"bar,omitempty" yaml:"bar,omitempty" mapstructure:"bar,omitempty"`

	// Baz corresponds to the JSON schema field "baz".
	Baz *bool `json:"baz,omitempty" yaml:"baz,omitempty" mapstructure:"baz,omitempty"`

	// Foo corresponds to the JSON schema field "foo".
	Foo *string `json:"foo,omitempty" yaml:"foo,omitempty" mapstructure:"foo,omitempty"`
}

type AnyOf2ConfigurationsElem_1 struct {
	// Bar corresponds to the JSON schema field "bar".
	Bar float64 `json:"bar" yaml:"bar" mapstructure:"bar"`
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *AnyOf2ConfigurationsElem_1) UnmarshalYAML(value *yaml.Node) error {
	var raw map[string]interface{}
	if err := value.Decode(&raw); err != nil {
		return err
	}
	if _, ok := raw["bar"]; raw != nil && !ok {
		return fmt.Errorf("field bar in AnyOf2ConfigurationsElem_1: required")
	}
	type Plain AnyOf2ConfigurationsElem_1
	var plain Plain
	if err := value.Decode(&plain); err != nil {
		return err
	}
	*j = AnyOf2ConfigurationsElem_1(plain)
	return nil
}

type AnyOf2ConfigurationsElem_0 = Foo

// UnmarshalJSON implements json.Unmarshaler.
func (j *AnyOf2ConfigurationsElem_1) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["bar"]; raw != nil && !ok {
		return fmt.Errorf("field bar in AnyOf2ConfigurationsElem_1: required")
	}
	type Plain AnyOf2ConfigurationsElem_1
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = AnyOf2ConfigurationsElem_1(plain)
	return nil
}

type AnyOf2ConfigurationsElem_2 struct {
	// Baz corresponds to the JSON schema field "baz".
	Baz *bool `json:"baz,omitempty" yaml:"baz,omitempty" mapstructure:"baz,omitempty"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *AnyOf2ConfigurationsElem_2) UnmarshalJSON(value []byte) error {
	type Plain AnyOf2ConfigurationsElem_2
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = AnyOf2ConfigurationsElem_2(plain)
	return nil
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *AnyOf2ConfigurationsElem_2) UnmarshalYAML(value *yaml.Node) error {
	type Plain AnyOf2ConfigurationsElem_2
	var plain Plain
	if err := value.Decode(&plain); err != nil {
		return err
	}
	*j = AnyOf2ConfigurationsElem_2(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *AnyOf2ConfigurationsElem) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	var anyOf2ConfigurationsElem_0 AnyOf2ConfigurationsElem_0
	var anyOf2ConfigurationsElem_1 AnyOf2ConfigurationsElem_1
	var anyOf2ConfigurationsElem_2 AnyOf2ConfigurationsElem_2
	var errs []error
	if err := anyOf2ConfigurationsElem_0.UnmarshalJSON(value); err != nil {
		errs = append(errs, err)
	}
	if err := anyOf2ConfigurationsElem_1.UnmarshalJSON(value); err != nil {
		errs = append(errs, err)
	}
	if err := anyOf2ConfigurationsElem_2.UnmarshalJSON(value); err != nil {
		errs = append(errs, err)
	}
	if len(errs) == 3 {
		return fmt.Errorf("all validators failed: %s", errors.Join(errs...))
	}
	type Plain AnyOf2ConfigurationsElem
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = AnyOf2ConfigurationsElem(plain)
	return nil
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *AnyOf2ConfigurationsElem) UnmarshalYAML(value *yaml.Node) error {
	var raw map[string]interface{}
	if err := value.Decode(&raw); err != nil {
		return err
	}
	var anyOf2ConfigurationsElem_0 AnyOf2ConfigurationsElem_0
	var anyOf2ConfigurationsElem_1 AnyOf2ConfigurationsElem_1
	var anyOf2ConfigurationsElem_2 AnyOf2ConfigurationsElem_2
	var errs []error
	if err := anyOf2ConfigurationsElem_0.UnmarshalYAML(value); err != nil {
		errs = append(errs, err)
	}
	if err := anyOf2ConfigurationsElem_1.UnmarshalYAML(value); err != nil {
		errs = append(errs, err)
	}
	if err := anyOf2ConfigurationsElem_2.UnmarshalYAML(value); err != nil {
		errs = append(errs, err)
	}
	if len(errs) == 3 {
		return fmt.Errorf("all validators failed: %s", errors.Join(errs...))
	}
	type Plain AnyOf2ConfigurationsElem
	var plain Plain
	if err := value.Decode(&plain); err != nil {
		return err
	}
	*j = AnyOf2ConfigurationsElem(plain)
	return nil
}

type Foo struct {
	// Foo corresponds to the JSON schema field "foo".
	Foo string `json:"foo" yaml:"foo" mapstructure:"foo"`
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *Foo) UnmarshalYAML(value *yaml.Node) error {
	var raw map[string]interface{}
	if err := value.Decode(&raw); err != nil {
		return err
	}
	if _, ok := raw["foo"]; raw != nil && !ok {
		return fmt.Errorf("field foo in Foo: required")
	}
	type Plain Foo
	var plain Plain
	if err := value.Decode(&plain); err != nil {
		return err
	}
	*j = Foo(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Foo) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["foo"]; raw != nil && !ok {
		return fmt.Errorf("field foo in Foo: required")
	}
	type Plain Foo
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = Foo(plain)
	return nil
}
