// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package test

import "encoding/json"
import "fmt"
import yaml "gopkg.in/yaml.v3"
import "reflect"

type RootConstNull struct {
	Value interface{}
}

// MarshalJSON implements json.Marshaler.
func (j *RootConstNull) MarshalJSON() ([]byte, error) {
	return json.Marshal(j.Value)
}

// MarshalYAML implements yaml.Marshal.
func (j *RootConstNull) MarshalYAML() (interface{}, error) {
	return j.Value, nil
}

var enumValues_RootConstNull = []interface{}{
	nil,
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *RootConstNull) UnmarshalJSON(value []byte) error {
	var v struct {
		Value interface{}
	}
	if err := json.Unmarshal(value, &v.Value); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_RootConstNull {
		if reflect.DeepEqual(v.Value, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_RootConstNull, v.Value)
	}
	*j = RootConstNull(v)
	return nil
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *RootConstNull) UnmarshalYAML(value *yaml.Node) error {
	var v struct {
		Value interface{}
	}
	if err := value.Decode(&v.Value); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_RootConstNull {
		if reflect.DeepEqual(v.Value, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_RootConstNull, v.Value)
	}
	*j = RootConstNull(v)
	return nil
}
