// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package test

import "encoding/json"
import "fmt"

type NumericRange struct {
	// MyInteger corresponds to the JSON schema field "myInteger".
	MyInteger int `json:"myInteger" yaml:"myInteger" mapstructure:"myInteger"`

	// MyNumber corresponds to the JSON schema field "myNumber".
	MyNumber float64 `json:"myNumber" yaml:"myNumber" mapstructure:"myNumber"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *NumericRange) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if _, ok := raw["myInteger"]; raw != nil && !ok {
		return fmt.Errorf("field myInteger in NumericRange: required")
	}
	if _, ok := raw["myNumber"]; raw != nil && !ok {
		return fmt.Errorf("field myNumber in NumericRange: required")
	}
	type Plain NumericRange
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	if plain.MyInteger < 2 {
		return fmt.Errorf("field %s: violates mimimum %s", "myInteger", "2")
	}
	if plain.MyInteger > 5 {
		return fmt.Errorf("field %s: violates maximum %s", "myInteger", "5")
	}
	if plain.MyNumber < 2.4 {
		return fmt.Errorf("field %s: violates mimimum %s", "myNumber", "2.4")
	}
	if plain.MyNumber > 5.6 {
		return fmt.Errorf("field %s: violates maximum %s", "myNumber", "5.6")
	}
	*j = NumericRange(plain)
	return nil
}
