// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package test

import "encoding/json"
import "fmt"
import yaml "gopkg.in/yaml.v3"
import "reflect"

// Integer enums declaring a sized format. Each validator decodes into the sized
// type and compares with reflect.DeepEqual, so the allowed-values list has to hold
// that type too: an untyped list holds ints, matched nothing, and rejected every
// value, valid ones included.
type IntegerFormatEnum struct {
	// Code corresponds to the JSON schema field "code".
	Code *IntegerFormatEnumCode `json:"code,omitempty,omitzero" yaml:"code,omitempty" mapstructure:"code,omitempty"`

	// Mixed corresponds to the JSON schema field "mixed".
	Mixed *IntegerFormatEnumMixed `json:"mixed,omitempty,omitzero" yaml:"mixed,omitempty" mapstructure:"mixed,omitempty"`

	// Wide corresponds to the JSON schema field "wide".
	Wide *IntegerFormatEnumWide `json:"wide,omitempty,omitzero" yaml:"wide,omitempty" mapstructure:"wide,omitempty"`
}

type IntegerFormatEnumCode int32

var enumValues_IntegerFormatEnumCode = []int32{
	66,
	67,
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *IntegerFormatEnumCode) UnmarshalJSON(value []byte) error {
	var v int32
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_IntegerFormatEnumCode {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_IntegerFormatEnumCode, v)
	}
	*j = IntegerFormatEnumCode(v)
	return nil
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *IntegerFormatEnumCode) UnmarshalYAML(value *yaml.Node) error {
	var v int32
	if err := value.Decode(&v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_IntegerFormatEnumCode {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_IntegerFormatEnumCode, v)
	}
	*j = IntegerFormatEnumCode(v)
	return nil
}

type IntegerFormatEnumMixed int32

var enumValues_IntegerFormatEnumMixed = []int32{
	66,
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *IntegerFormatEnumMixed) UnmarshalJSON(value []byte) error {
	var v int32
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_IntegerFormatEnumMixed {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_IntegerFormatEnumMixed, v)
	}
	*j = IntegerFormatEnumMixed(v)
	return nil
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *IntegerFormatEnumMixed) UnmarshalYAML(value *yaml.Node) error {
	var v int32
	if err := value.Decode(&v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_IntegerFormatEnumMixed {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_IntegerFormatEnumMixed, v)
	}
	*j = IntegerFormatEnumMixed(v)
	return nil
}

type IntegerFormatEnumWide int64

var enumValues_IntegerFormatEnumWide = []int64{
	1643178300132,
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *IntegerFormatEnumWide) UnmarshalJSON(value []byte) error {
	var v int64
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_IntegerFormatEnumWide {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_IntegerFormatEnumWide, v)
	}
	*j = IntegerFormatEnumWide(v)
	return nil
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *IntegerFormatEnumWide) UnmarshalYAML(value *yaml.Node) error {
	var v int64
	if err := value.Decode(&v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_IntegerFormatEnumWide {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_IntegerFormatEnumWide, v)
	}
	*j = IntegerFormatEnumWide(v)
	return nil
}
