// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package test

import "encoding/json"
import "fmt"
import yaml "gopkg.in/yaml.v3"

// A named nullable integer with a pinned width, which generates a named pointer
// alias. A default on a property referencing it needs a temp of the POINTEE's type
// — `&` on an int temp is not assignable to a *int64.
type IntFmtCountThing *int64

type IntegerFormatPointerDefault struct {
	// Count corresponds to the JSON schema field "count".
	Count IntFmtCountThing `json:"count,omitempty,omitzero" yaml:"count,omitempty" mapstructure:"count,omitempty"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *IntegerFormatPointerDefault) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return fmt.Errorf("unmarshal raw IntegerFormatPointerDefault: %w", err)
	}
	type Plain IntegerFormatPointerDefault
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return fmt.Errorf("unmarshal IntegerFormatPointerDefault: %w", err)
	}
	if v, ok := raw["count"]; !ok || v == nil {
		var defaultCount int64 = 5
		plain.Count = &defaultCount

	}
	*j = IntegerFormatPointerDefault(plain)
	return nil
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *IntegerFormatPointerDefault) UnmarshalYAML(value *yaml.Node) error {
	var raw map[string]interface{}
	if err := value.Decode(&raw); err != nil {
		return fmt.Errorf("unmarshal raw IntegerFormatPointerDefault: %w", err)
	}
	type Plain IntegerFormatPointerDefault
	var plain Plain
	if err := value.Decode(&plain); err != nil {
		return fmt.Errorf("unmarshal IntegerFormatPointerDefault: %w", err)
	}
	if v, ok := raw["count"]; !ok || v == nil {
		var defaultCount int64 = 5
		plain.Count = &defaultCount

	}
	*j = IntegerFormatPointerDefault(plain)
	return nil
}
