// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package test

import "encoding/json"
import "fmt"
import yaml "gopkg.in/yaml.v3"
import "reflect"

type CanonicalFragment map[string]interface{}

type Consumer struct {
	// Envelope corresponds to the JSON schema field "envelope".
	Envelope *Envelope `json:"envelope,omitempty,omitzero" yaml:"envelope,omitempty" mapstructure:"envelope,omitempty"`

	// Priority corresponds to the JSON schema field "priority".
	Priority *JobPriority `json:"priority,omitempty,omitzero" yaml:"priority,omitempty" mapstructure:"priority,omitempty"`
}

type Envelope struct {
	// MessageId corresponds to the JSON schema field "messageId".
	MessageId string `json:"messageId" yaml:"messageId" mapstructure:"messageId"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Envelope) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return fmt.Errorf("unmarshal raw Envelope: %w", err)
	}
	if _, ok := raw["messageId"]; raw != nil && !ok {
		return fmt.Errorf("field messageId in Envelope: required")
	}
	type Plain Envelope
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return fmt.Errorf("unmarshal Envelope: %w", err)
	}
	*j = Envelope(plain)
	return nil
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *Envelope) UnmarshalYAML(value *yaml.Node) error {
	var raw map[string]interface{}
	if err := value.Decode(&raw); err != nil {
		return fmt.Errorf("unmarshal raw Envelope: %w", err)
	}
	if _, ok := raw["messageId"]; raw != nil && !ok {
		return fmt.Errorf("field messageId in Envelope: required")
	}
	type Plain Envelope
	var plain Plain
	if err := value.Decode(&plain); err != nil {
		return fmt.Errorf("unmarshal Envelope: %w", err)
	}
	*j = Envelope(plain)
	return nil
}

type JobPriority string

const JobPriorityHigh JobPriority = "high"
const JobPriorityLow JobPriority = "low"
const JobPriorityMedium JobPriority = "medium"

var enumValues_JobPriority = []interface{}{
	"low",
	"medium",
	"high",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *JobPriority) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_JobPriority {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_JobPriority, v)
	}
	*j = JobPriority(v)
	return nil
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *JobPriority) UnmarshalYAML(value *yaml.Node) error {
	var v string
	if err := value.Decode(&v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_JobPriority {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_JobPriority, v)
	}
	*j = JobPriority(v)
	return nil
}
