// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package test

type ExtensionTags struct {
	// An integer past 2^53. Decoding into `any` would round it to ...992; the value
	// is kept undecoded so the literal the author wrote is what reaches the tag.
	BigId *int `json:"bigId,omitempty,omitzero" yaml:"bigId,omitempty" mapstructure:"bigId,omitempty" precision:"9007199254740993"`

	// Booleans render as true/false.
	Derived *bool `json:"derived,omitempty,omitzero" yaml:"derived,omitempty" mapstructure:"derived,omitempty" derived:"true"`

	// A string extension becomes a struct tag, so a reflection-based consumer can
	// read what the number means. Without this the declaration is dropped and the
	// generated type is unusable with such a consumer.
	OilRate *float64 `json:"oilRate,omitempty,omitzero" yaml:"oilRate,omitempty" mapstructure:"oilRate,omitempty" slb-measurement:"Volume_Flowrate"`

	// No extensions at all, so the tags are unchanged.
	Plain *string `json:"plain,omitempty,omitzero" yaml:"plain,omitempty" mapstructure:"plain,omitempty"`

	// Numbers render without a trailing .0, which is what a reader parsing the tag
	// back would expect.
	Precision *float64 `json:"precision,omitempty,omitzero" yaml:"precision,omitempty" mapstructure:"precision,omitempty" precision:"3"`

	// Values are quoted with strconv.Quote, so an embedded quote is escaped rather
	// than closing the tag early and silently changing what reflection reads back.
	Quoted *string `json:"quoted,omitempty,omitzero" yaml:"quoted,omitempty" mapstructure:"quoted,omitempty" slb-measurement:"has \"quotes\" inside"`

	// Only extensions named in the configuration are emitted; this one is not mapped,
	// so it stays out of the output.
	Unmapped *string `json:"unmapped,omitempty,omitzero" yaml:"unmapped,omitempty" mapstructure:"unmapped,omitempty"`
}
