// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package test

import "encoding/json"
import "fmt"
import yaml "gopkg.in/yaml.v3"

type EnumIfNullValue struct {
	// Details corresponds to the JSON schema field "details".
	Details *string `json:"details,omitempty,omitzero" yaml:"details,omitempty" mapstructure:"details,omitempty"`

	// Kind corresponds to the JSON schema field "kind".
	Kind string `json:"kind" yaml:"kind" mapstructure:"kind"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *EnumIfNullValue) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return fmt.Errorf("unmarshal raw EnumIfNullValue: %w", err)
	}
	if _, ok := raw["kind"]; raw != nil && !ok {
		return fmt.Errorf("field kind in EnumIfNullValue: required")
	}
	type Plain EnumIfNullValue
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return fmt.Errorf("unmarshal EnumIfNullValue: %w", err)
	}
	*j = EnumIfNullValue(plain)
	return nil
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *EnumIfNullValue) UnmarshalYAML(value *yaml.Node) error {
	var raw map[string]interface{}
	if err := value.Decode(&raw); err != nil {
		return fmt.Errorf("unmarshal raw EnumIfNullValue: %w", err)
	}
	if _, ok := raw["kind"]; raw != nil && !ok {
		return fmt.Errorf("field kind in EnumIfNullValue: required")
	}
	type Plain EnumIfNullValue
	var plain Plain
	if err := value.Decode(&plain); err != nil {
		return fmt.Errorf("unmarshal EnumIfNullValue: %w", err)
	}
	*j = EnumIfNullValue(plain)
	return nil
}
