// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package test

import "encoding/json"
import "errors"
import "fmt"
import yaml "gopkg.in/yaml.v3"

type Thing struct {
	// Values corresponds to the JSON schema field "values".
	Values []Value `json:"values,omitempty" yaml:"values,omitempty" mapstructure:"values,omitempty"`
}

type Thing_0 struct {
	// Values corresponds to the JSON schema field "values".
	Values []Value `json:"values,omitempty" yaml:"values,omitempty" mapstructure:"values,omitempty"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Thing_0) UnmarshalJSON(value []byte) error {
	type Plain Thing_0
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = Thing_0(plain)
	return nil
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *Thing_0) UnmarshalYAML(value *yaml.Node) error {
	type Plain Thing_0
	var plain Plain
	if err := value.Decode(&plain); err != nil {
		return err
	}
	*j = Thing_0(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Thing) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	var thing_0 Thing_0
	var errs []error
	if err := thing_0.UnmarshalJSON(value); err != nil {
		errs = append(errs, err)
	}
	if len(errs) == 1 {
		return fmt.Errorf("all validators failed: %s", errors.Join(errs...))
	}
	type Plain Thing
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = Thing(plain)
	return nil
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *Thing) UnmarshalYAML(value *yaml.Node) error {
	var raw map[string]interface{}
	if err := value.Decode(&raw); err != nil {
		return err
	}
	var thing_0 Thing_0
	var errs []error
	if err := thing_0.UnmarshalYAML(value); err != nil {
		errs = append(errs, err)
	}
	if len(errs) == 1 {
		return fmt.Errorf("all validators failed: %s", errors.Join(errs...))
	}
	type Plain Thing
	var plain Plain
	if err := value.Decode(&plain); err != nil {
		return err
	}
	*j = Thing(plain)
	return nil
}

type Value float64

type AnyOf = Thing
