// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package test

import "encoding/json"
import "fmt"
import yaml "gopkg.in/yaml.v3"

type StrictShape struct {
	// Value corresponds to the JSON schema field "value".
	Value StrictShapeValue `json:"value" yaml:"value" mapstructure:"value"`
}

type StrictShapeValue struct {
	Variant0 *StrictShapeValueVariant0 `json:"-" yaml:"-"`

	Variant1 *StrictShapeValueVariant1 `json:"-" yaml:"-"`
}

type StrictShapeValueVariant0 struct {
	// Age corresponds to the JSON schema field "age".
	Age *int `json:"age,omitempty,omitzero" yaml:"age,omitempty" mapstructure:"age,omitempty"`

	// Name corresponds to the JSON schema field "name".
	Name string `json:"name" yaml:"name" mapstructure:"name"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *StrictShapeValueVariant0) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return fmt.Errorf("unmarshal raw StrictShapeValueVariant0: %w", err)
	}
	if _, ok := raw["name"]; raw != nil && !ok {
		return fmt.Errorf("field name in StrictShapeValueVariant0: required")
	}
	type Plain StrictShapeValueVariant0
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return fmt.Errorf("unmarshal StrictShapeValueVariant0: %w", err)
	}
	*j = StrictShapeValueVariant0(plain)
	return nil
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *StrictShapeValueVariant0) UnmarshalYAML(value *yaml.Node) error {
	var raw map[string]interface{}
	if err := value.Decode(&raw); err != nil {
		return fmt.Errorf("unmarshal raw StrictShapeValueVariant0: %w", err)
	}
	if _, ok := raw["name"]; raw != nil && !ok {
		return fmt.Errorf("field name in StrictShapeValueVariant0: required")
	}
	type Plain StrictShapeValueVariant0
	var plain Plain
	if err := value.Decode(&plain); err != nil {
		return fmt.Errorf("unmarshal StrictShapeValueVariant0: %w", err)
	}
	*j = StrictShapeValueVariant0(plain)
	return nil
}

type StrictShapeValueVariant1 struct {
	// Label corresponds to the JSON schema field "label".
	Label *string `json:"label,omitempty,omitzero" yaml:"label,omitempty" mapstructure:"label,omitempty"`

	// Name corresponds to the JSON schema field "name".
	Name string `json:"name" yaml:"name" mapstructure:"name"`
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *StrictShapeValueVariant1) UnmarshalYAML(value *yaml.Node) error {
	var raw map[string]interface{}
	if err := value.Decode(&raw); err != nil {
		return fmt.Errorf("unmarshal raw StrictShapeValueVariant1: %w", err)
	}
	if _, ok := raw["name"]; raw != nil && !ok {
		return fmt.Errorf("field name in StrictShapeValueVariant1: required")
	}
	type Plain StrictShapeValueVariant1
	var plain Plain
	if err := value.Decode(&plain); err != nil {
		return fmt.Errorf("unmarshal StrictShapeValueVariant1: %w", err)
	}
	*j = StrictShapeValueVariant1(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *StrictShapeValueVariant1) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return fmt.Errorf("unmarshal raw StrictShapeValueVariant1: %w", err)
	}
	if _, ok := raw["name"]; raw != nil && !ok {
		return fmt.Errorf("field name in StrictShapeValueVariant1: required")
	}
	type Plain StrictShapeValueVariant1
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return fmt.Errorf("unmarshal StrictShapeValueVariant1: %w", err)
	}
	*j = StrictShapeValueVariant1(plain)
	return nil
}

// MarshalJSON implements json.Marshaler. Exactly one variant
// pointer must be non-nil; otherwise marshaling errors.
func (j StrictShapeValue) MarshalJSON() ([]byte, error) {
	set := 0
	if j.Variant0 != nil {
		set++
	}
	if j.Variant1 != nil {
		set++
	}
	if set != 1 {
		return nil, fmt.Errorf("StrictShapeValue: exactly one variant must be set, got %d", set)
	}
	if j.Variant0 != nil {
		return json.Marshal(j.Variant0)
	}
	if j.Variant1 != nil {
		return json.Marshal(j.Variant1)
	}
	return nil, nil // unreachable
}

// MarshalYAML mirrors MarshalJSON.
func (j StrictShapeValue) MarshalYAML() (interface{}, error) {
	set := 0
	if j.Variant0 != nil {
		set++
	}
	if j.Variant1 != nil {
		set++
	}
	if set != 1 {
		return nil, fmt.Errorf("StrictShapeValue: exactly one variant must be set, got %d", set)
	}
	if j.Variant0 != nil {
		return j.Variant0, nil
	}
	if j.Variant1 != nil {
		return j.Variant1, nil
	}
	return nil, nil // unreachable
}

// UnmarshalJSON implements json.Unmarshaler. With no natural
// discriminator we try each variant in turn after a per-variant shape check;
// success requires exactly one variant to unmarshal without error.
func (j *StrictShapeValue) UnmarshalJSON(value []byte) error {
	// Reset to zero value so reusing the same holder across multiple
	// Unmarshal calls doesn't leave a previous winner set alongside the
	// new one (which would violate the one-variant-set invariant and
	// break the corresponding Marshal).
	*j = StrictShapeValue{}
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return fmt.Errorf("unmarshal StrictShapeValue: %w", err)
	}
	matched := 0
	var lastErr error

	// Variant 0: StrictShapeValueVariant0
	{
		shapeOK := true
		if _, ok := raw["name"]; !ok {
			shapeOK = false
		}
		for k := range raw {
			switch k {
			case "age", "name":
			default:
				shapeOK = false
			}
		}
		if shapeOK {
			var v StrictShapeValueVariant0
			if err := json.Unmarshal(value, &v); err == nil {
				j.Variant0 = &v
				matched++
			} else {
				lastErr = err
			}
		}
	}

	// Variant 1: StrictShapeValueVariant1
	{
		shapeOK := true
		if _, ok := raw["name"]; !ok {
			shapeOK = false
		}
		for k := range raw {
			switch k {
			case "label", "name":
			default:
				shapeOK = false
			}
		}
		if shapeOK {
			var v StrictShapeValueVariant1
			if err := json.Unmarshal(value, &v); err == nil {
				j.Variant1 = &v
				matched++
			} else {
				lastErr = err
			}
		}
	}

	if matched == 0 {
		if lastErr != nil {
			return fmt.Errorf("StrictShapeValue: no oneOf variant matched: %w", lastErr)
		}
		return fmt.Errorf("StrictShapeValue: no oneOf variant matched")
	}
	if matched > 1 {
		j.Variant0 = nil
		j.Variant1 = nil
		return fmt.Errorf("StrictShapeValue: ambiguous input — %d oneOf variants matched", matched)
	}
	return nil
}

// UnmarshalYAML mirrors UnmarshalJSON: try each variant after a
// shape check; exactly one must unmarshal without error.
// success requires exactly one variant to unmarshal without error.
func (j *StrictShapeValue) UnmarshalYAML(value *yaml.Node) error {
	// Reset to zero value so reusing the same holder across multiple
	// Unmarshal calls doesn't leave a previous winner set alongside the
	// new one (which would violate the one-variant-set invariant and
	// break the corresponding Marshal).
	*j = StrictShapeValue{}
	var raw map[string]interface{}
	if err := value.Decode(&raw); err != nil {
		return fmt.Errorf("unmarshal StrictShapeValue: %w", err)
	}
	matched := 0
	var lastErr error

	// Variant 0: StrictShapeValueVariant0
	{
		shapeOK := true
		if _, ok := raw["name"]; !ok {
			shapeOK = false
		}
		for k := range raw {
			switch k {
			case "age", "name":
			default:
				shapeOK = false
			}
		}
		if shapeOK {
			var v StrictShapeValueVariant0
			if err := value.Decode(&v); err == nil {
				j.Variant0 = &v
				matched++
			} else {
				lastErr = err
			}
		}
	}

	// Variant 1: StrictShapeValueVariant1
	{
		shapeOK := true
		if _, ok := raw["name"]; !ok {
			shapeOK = false
		}
		for k := range raw {
			switch k {
			case "label", "name":
			default:
				shapeOK = false
			}
		}
		if shapeOK {
			var v StrictShapeValueVariant1
			if err := value.Decode(&v); err == nil {
				j.Variant1 = &v
				matched++
			} else {
				lastErr = err
			}
		}
	}

	if matched == 0 {
		if lastErr != nil {
			return fmt.Errorf("StrictShapeValue: no oneOf variant matched: %w", lastErr)
		}
		return fmt.Errorf("StrictShapeValue: no oneOf variant matched")
	}
	if matched > 1 {
		j.Variant0 = nil
		j.Variant1 = nil
		return fmt.Errorf("StrictShapeValue: ambiguous input — %d oneOf variants matched", matched)
	}
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *StrictShape) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return fmt.Errorf("unmarshal raw StrictShape: %w", err)
	}
	if _, ok := raw["value"]; raw != nil && !ok {
		return fmt.Errorf("field value in StrictShape: required")
	}
	type Plain StrictShape
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return fmt.Errorf("unmarshal StrictShape: %w", err)
	}
	*j = StrictShape(plain)
	return nil
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *StrictShape) UnmarshalYAML(value *yaml.Node) error {
	var raw map[string]interface{}
	if err := value.Decode(&raw); err != nil {
		return fmt.Errorf("unmarshal raw StrictShape: %w", err)
	}
	if _, ok := raw["value"]; raw != nil && !ok {
		return fmt.Errorf("field value in StrictShape: required")
	}
	type Plain StrictShape
	var plain Plain
	if err := value.Decode(&plain); err != nil {
		return fmt.Errorf("unmarshal StrictShape: %w", err)
	}
	*j = StrictShape(plain)
	return nil
}
