// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package test

import "bytes"
import "encoding/json"
import "fmt"
import yaml "gopkg.in/yaml.v3"

type StringNumberBoolNull struct {
	value interface{}

	present bool
}

// AsBool returns the value as a bool and reports whether it was a bool.
func (j *StringNumberBoolNull) AsBool() (bool, bool) {
	if j == nil || !j.present {
		return false, false
	}
	v, ok := j.value.(bool)
	return v, ok
}

// AsNumber returns the value as a float64 and reports whether it was numeric.
func (j *StringNumberBoolNull) AsNumber() (float64, bool) {
	if j == nil || !j.present {
		return 0, false
	}
	v, ok := j.value.(float64)
	return v, ok
}

// AsString returns the value as a string and reports whether it was a string.
func (j *StringNumberBoolNull) AsString() (string, bool) {
	if j == nil || !j.present {
		return "", false
	}
	v, ok := j.value.(string)
	return v, ok
}

// IsNull reports whether the wrapper was populated with an explicit JSON `null`.
// Returns false for unset wrappers (use IsZero) and for wrappers holding a
// non-null primitive.
func (j *StringNumberBoolNull) IsNull() bool {
	return j != nil && j.present && j.value == nil
}

// IsZero reports whether the wrapper has not been populated by
// Unmarshal{JSON,YAML}; supports the encoding/json `omitzero` tag. Note: an
// explicitly-decoded JSON `null` is NOT zero — see IsNull.
func (j *StringNumberBoolNull) IsZero() bool {
	return j == nil || !j.present
}

// MarshalJSON implements json.Marshaler.
func (j *StringNumberBoolNull) MarshalJSON() ([]byte, error) {
	if j == nil || !j.present {
		return []byte("null"), nil
	}
	if j.value == nil {
		return []byte("null"), nil
	}
	return json.Marshal(j.value)
}

// MarshalYAML implements yaml.Marshaler.
func (j *StringNumberBoolNull) MarshalYAML() (interface{}, error) {
	if j == nil || !j.present {
		return nil, nil
	}
	return j.value, nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *StringNumberBoolNull) UnmarshalJSON(value []byte) error {
	dec := json.NewDecoder(bytes.NewReader(value))
	dec.UseNumber()
	tok, err := dec.Token()
	if err != nil {
		return err
	}
	switch tok.(type) {
	case string:
		var v string
		if err := json.Unmarshal(value, &v); err != nil {
			return err
		}
		j.value = v
	case json.Number:
		var v float64
		if err := json.Unmarshal(value, &v); err != nil {
			return err
		}
		j.value = v
	case bool:
		var v bool
		if err := json.Unmarshal(value, &v); err != nil {
			return err
		}
		j.value = v
	case nil:
		var v any
		if err := json.Unmarshal(value, &v); err != nil {
			return err
		}
		j.value = nil
	default:
		return fmt.Errorf("StringNumberBoolNull: unsupported JSON value of type %T", tok)
	}
	j.present = true
	return nil
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *StringNumberBoolNull) UnmarshalYAML(value *yaml.Node) error {
	if value.Kind != yaml.ScalarNode {
		return fmt.Errorf("StringNumberBoolNull: expected scalar YAML node")
	}
	switch value.Tag {
	case "!!str":
		var v string
		if err := value.Decode(&v); err != nil {
			return err
		}
		j.value = v
	case "!!int", "!!float":
		var v float64
		if err := value.Decode(&v); err != nil {
			return err
		}
		j.value = v
	case "!!bool":
		var v bool
		if err := value.Decode(&v); err != nil {
			return err
		}
		j.value = v
	case "!!null":
		j.value = nil
	default:
		return fmt.Errorf("StringNumberBoolNull: unsupported YAML scalar tag %q", value.Tag)
	}
	j.present = true
	return nil
}

// Value returns the decoded primitive payload.
func (j *StringNumberBoolNull) Value() any {
	if j == nil {
		return nil
	}
	return j.value
}
