// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package test

import "encoding/json"
import "fmt"
import yaml "gopkg.in/yaml.v3"

type EnumIfMixedTypes struct {
	// Details corresponds to the JSON schema field "details".
	Details *string `json:"details,omitempty,omitzero" yaml:"details,omitempty" mapstructure:"details,omitempty"`

	// Kind corresponds to the JSON schema field "kind".
	Kind string `json:"kind" yaml:"kind" mapstructure:"kind"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *EnumIfMixedTypes) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return fmt.Errorf("unmarshal raw EnumIfMixedTypes: %w", err)
	}
	if _, ok := raw["kind"]; raw != nil && !ok {
		return fmt.Errorf("field kind in EnumIfMixedTypes: required")
	}
	type Plain EnumIfMixedTypes
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return fmt.Errorf("unmarshal EnumIfMixedTypes: %w", err)
	}
	*j = EnumIfMixedTypes(plain)
	return nil
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *EnumIfMixedTypes) UnmarshalYAML(value *yaml.Node) error {
	var raw map[string]interface{}
	if err := value.Decode(&raw); err != nil {
		return fmt.Errorf("unmarshal raw EnumIfMixedTypes: %w", err)
	}
	if _, ok := raw["kind"]; raw != nil && !ok {
		return fmt.Errorf("field kind in EnumIfMixedTypes: required")
	}
	type Plain EnumIfMixedTypes
	var plain Plain
	if err := value.Decode(&plain); err != nil {
		return fmt.Errorf("unmarshal EnumIfMixedTypes: %w", err)
	}
	*j = EnumIfMixedTypes(plain)
	return nil
}
