// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package test

import "bytes"
import "encoding/json"
import "fmt"
import yaml "gopkg.in/yaml.v3"

type NumStringBool struct {
	// Value corresponds to the JSON schema field "value".
	Value NumStringBoolValue `json:"value" yaml:"value" mapstructure:"value"`
}

type NumStringBoolValue struct {
	value interface{}

	present bool
}

// AsBool returns the value as a bool and reports whether it was a bool.
func (j *NumStringBoolValue) AsBool() (bool, bool) {
	if j == nil || !j.present {
		return false, false
	}
	v, ok := j.value.(bool)
	return v, ok
}

// AsNumber returns the value as a float64 and reports whether it was numeric.
func (j *NumStringBoolValue) AsNumber() (float64, bool) {
	if j == nil || !j.present {
		return 0, false
	}
	v, ok := j.value.(float64)
	return v, ok
}

// AsString returns the value as a string and reports whether it was a string.
func (j *NumStringBoolValue) AsString() (string, bool) {
	if j == nil || !j.present {
		return "", false
	}
	v, ok := j.value.(string)
	return v, ok
}

// IsZero reports whether the wrapper has not been populated by
// Unmarshal{JSON,YAML}; supports the encoding/json `omitzero` tag.
func (j *NumStringBoolValue) IsZero() bool {
	return j == nil || !j.present
}

// MarshalJSON implements json.Marshaler.
func (j *NumStringBoolValue) MarshalJSON() ([]byte, error) {
	if j == nil || !j.present {
		return nil, fmt.Errorf("NumStringBoolValue: cannot marshal unset value (schema does not allow null)")
	}
	if j.value == nil {
		return nil, fmt.Errorf("NumStringBoolValue: cannot marshal nil value (schema does not allow null)")
	}
	return json.Marshal(j.value)
}

// MarshalYAML implements yaml.Marshaler.
func (j *NumStringBoolValue) MarshalYAML() (interface{}, error) {
	if j == nil || !j.present {
		return nil, fmt.Errorf("NumStringBoolValue: cannot marshal unset value (schema does not allow null)")
	}
	if j.value == nil {
		return nil, fmt.Errorf("NumStringBoolValue: cannot marshal nil value (schema does not allow null)")
	}
	return j.value, nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *NumStringBoolValue) UnmarshalJSON(value []byte) error {
	dec := json.NewDecoder(bytes.NewReader(value))
	dec.UseNumber()
	tok, err := dec.Token()
	if err != nil {
		return err
	}
	switch tok.(type) {
	case string:
		var v string
		if err := json.Unmarshal(value, &v); err != nil {
			return err
		}
		j.value = v
	case json.Number:
		var v float64
		if err := json.Unmarshal(value, &v); err != nil {
			return err
		}
		j.value = v
	case bool:
		var v bool
		if err := json.Unmarshal(value, &v); err != nil {
			return err
		}
		j.value = v
	default:
		return fmt.Errorf("NumStringBoolValue: unsupported JSON value of type %T", tok)
	}
	j.present = true
	return nil
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *NumStringBoolValue) UnmarshalYAML(value *yaml.Node) error {
	if value.Kind != yaml.ScalarNode {
		return fmt.Errorf("NumStringBoolValue: expected scalar YAML node")
	}
	switch value.Tag {
	case "!!str":
		var v string
		if err := value.Decode(&v); err != nil {
			return err
		}
		j.value = v
	case "!!int", "!!float":
		var v float64
		if err := value.Decode(&v); err != nil {
			return err
		}
		j.value = v
	case "!!bool":
		var v bool
		if err := value.Decode(&v); err != nil {
			return err
		}
		j.value = v
	default:
		return fmt.Errorf("NumStringBoolValue: unsupported YAML scalar tag %q", value.Tag)
	}
	j.present = true
	return nil
}

// Value returns the decoded primitive payload.
func (j *NumStringBoolValue) Value() any {
	if j == nil {
		return nil
	}
	return j.value
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *NumStringBool) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return fmt.Errorf("unmarshal raw NumStringBool: %w", err)
	}
	if _, ok := raw["value"]; raw != nil && !ok {
		return fmt.Errorf("field value in NumStringBool: required")
	}
	type Plain NumStringBool
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return fmt.Errorf("unmarshal NumStringBool: %w", err)
	}
	*j = NumStringBool(plain)
	return nil
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *NumStringBool) UnmarshalYAML(value *yaml.Node) error {
	var raw map[string]interface{}
	if err := value.Decode(&raw); err != nil {
		return fmt.Errorf("unmarshal raw NumStringBool: %w", err)
	}
	if _, ok := raw["value"]; raw != nil && !ok {
		return fmt.Errorf("field value in NumStringBool: required")
	}
	type Plain NumStringBool
	var plain Plain
	if err := value.Decode(&plain); err != nil {
		return fmt.Errorf("unmarshal NumStringBool: %w", err)
	}
	*j = NumStringBool(plain)
	return nil
}
