// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package test

import "encoding/json"
import "fmt"
import yaml "gopkg.in/yaml.v3"
import "reflect"

type EnumIfWithElse struct {
	// BillingId corresponds to the JSON schema field "billingId".
	BillingId *string `json:"billingId,omitempty,omitzero" yaml:"billingId,omitempty" mapstructure:"billingId,omitempty"`

	// FreeReason corresponds to the JSON schema field "freeReason".
	FreeReason *string `json:"freeReason,omitempty,omitzero" yaml:"freeReason,omitempty" mapstructure:"freeReason,omitempty"`

	// Tier corresponds to the JSON schema field "tier".
	Tier EnumIfWithElseTier `json:"tier" yaml:"tier" mapstructure:"tier"`
}

type EnumIfWithElseTier string

const EnumIfWithElseTierFree EnumIfWithElseTier = "free"
const EnumIfWithElseTierGold EnumIfWithElseTier = "gold"
const EnumIfWithElseTierPremium EnumIfWithElseTier = "premium"
const EnumIfWithElseTierSilver EnumIfWithElseTier = "silver"

var enumValues_EnumIfWithElseTier = []interface{}{
	"premium",
	"gold",
	"silver",
	"free",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *EnumIfWithElseTier) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_EnumIfWithElseTier {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_EnumIfWithElseTier, v)
	}
	*j = EnumIfWithElseTier(v)
	return nil
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *EnumIfWithElseTier) UnmarshalYAML(value *yaml.Node) error {
	var v string
	if err := value.Decode(&v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_EnumIfWithElseTier {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_EnumIfWithElseTier, v)
	}
	*j = EnumIfWithElseTier(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *EnumIfWithElse) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return fmt.Errorf("unmarshal raw EnumIfWithElse: %w", err)
	}
	if _, ok := raw["tier"]; raw != nil && !ok {
		return fmt.Errorf("field tier in EnumIfWithElse: required")
	}
	rawDisc, hasDisc := raw["tier"]
	if hasDisc {
		discStr, isStr := rawDisc.(string)
		if !isStr {
			return fmt.Errorf("field tier in EnumIfWithElse: must be a string for discriminator dispatch")
		}
		if discStr == "premium" || discStr == "gold" || discStr == "silver" {
			if _, ok := raw["billingId"]; !ok {
				return fmt.Errorf("field billingId in EnumIfWithElse (when tier='%s'): required", discStr)
			}
		} else {
			if _, ok := raw["freeReason"]; !ok {
				return fmt.Errorf("field freeReason in EnumIfWithElse (when tier!='%s'): required", discStr)
			}
		}
	}
	type Plain EnumIfWithElse
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return fmt.Errorf("unmarshal EnumIfWithElse: %w", err)
	}
	*j = EnumIfWithElse(plain)
	return nil
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *EnumIfWithElse) UnmarshalYAML(value *yaml.Node) error {
	var raw map[string]interface{}
	if err := value.Decode(&raw); err != nil {
		return fmt.Errorf("unmarshal raw EnumIfWithElse: %w", err)
	}
	if _, ok := raw["tier"]; raw != nil && !ok {
		return fmt.Errorf("field tier in EnumIfWithElse: required")
	}
	rawDisc, hasDisc := raw["tier"]
	if hasDisc {
		discStr, isStr := rawDisc.(string)
		if !isStr {
			return fmt.Errorf("field tier in EnumIfWithElse: must be a string for discriminator dispatch")
		}
		if discStr == "premium" || discStr == "gold" || discStr == "silver" {
			if _, ok := raw["billingId"]; !ok {
				return fmt.Errorf("field billingId in EnumIfWithElse (when tier='%s'): required", discStr)
			}
		} else {
			if _, ok := raw["freeReason"]; !ok {
				return fmt.Errorf("field freeReason in EnumIfWithElse (when tier!='%s'): required", discStr)
			}
		}
	}
	type Plain EnumIfWithElse
	var plain Plain
	if err := value.Decode(&plain); err != nil {
		return fmt.Errorf("unmarshal EnumIfWithElse: %w", err)
	}
	*j = EnumIfWithElse(plain)
	return nil
}
