// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package test

import "encoding/json"
import "fmt"
import yaml "gopkg.in/yaml.v3"

// Property names are schema data, not identifiers, so they can carry characters
// that are not safe to drop into generated Go source. Interpolated raw, a quote or
// backslash ends the string literal early and the file does not compile; a percent
// sign is read by fmt as a verb.
type PropertyNameEscaping struct {
	// AB corresponds to the JSON schema field "a\"b".
	AB string `json:"a"b" yaml:"a"b" mapstructure:"a"b"`

	// BackSlash corresponds to the JSON schema field "back\\slash".
	BackSlash string `json:"back\slash" yaml:"back\slash" mapstructure:"back\slash"`

	// Ordinary corresponds to the JSON schema field "ordinary".
	Ordinary string `json:"ordinary" yaml:"ordinary" mapstructure:"ordinary"`

	// PctS corresponds to the JSON schema field "pct%s".
	PctS string `json:"pct%s" yaml:"pct%s" mapstructure:"pct%s"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *PropertyNameEscaping) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["a\"b"]; raw != nil && !ok {
		return fmt.Errorf("field a\"b in PropertyNameEscaping: required")
	}
	if _, ok := raw["back\\slash"]; raw != nil && !ok {
		return fmt.Errorf("field back\\slash in PropertyNameEscaping: required")
	}
	if _, ok := raw["ordinary"]; raw != nil && !ok {
		return fmt.Errorf("field ordinary in PropertyNameEscaping: required")
	}
	if _, ok := raw["pct%s"]; raw != nil && !ok {
		return fmt.Errorf("field pct%%s in PropertyNameEscaping: required")
	}
	type Plain PropertyNameEscaping
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = PropertyNameEscaping(plain)
	return nil
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *PropertyNameEscaping) UnmarshalYAML(value *yaml.Node) error {
	var raw map[string]interface{}
	if err := value.Decode(&raw); err != nil {
		return err
	}
	if _, ok := raw["a\"b"]; raw != nil && !ok {
		return fmt.Errorf("field a\"b in PropertyNameEscaping: required")
	}
	if _, ok := raw["back\\slash"]; raw != nil && !ok {
		return fmt.Errorf("field back\\slash in PropertyNameEscaping: required")
	}
	if _, ok := raw["ordinary"]; raw != nil && !ok {
		return fmt.Errorf("field ordinary in PropertyNameEscaping: required")
	}
	if _, ok := raw["pct%s"]; raw != nil && !ok {
		return fmt.Errorf("field pct%%s in PropertyNameEscaping: required")
	}
	type Plain PropertyNameEscaping
	var plain Plain
	if err := value.Decode(&plain); err != nil {
		return err
	}
	*j = PropertyNameEscaping(plain)
	return nil
}
