// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package test

import "encoding/json"
import "fmt"
import yaml "gopkg.in/yaml.v3"

// Property names encoding/json accepts in a struct tag. They still need escaping
// on the way into generated Go: a percent sign is read by fmt as a verb unless
// doubled, and the name is emitted into both map keys and error messages.
type PropertyNameEscaping struct {
	// An array whose name carries a percent. The length check keeps the name as an
	// argument rather than splicing it into the format string, so the percent is
	// never read as a verb.
	ArrPctS [][]string `json:"arrPct%s" yaml:"arrPct%s" mapstructure:"arrPct%s"`

	// Ordinary corresponds to the JSON schema field "ordinary".
	Ordinary string `json:"ordinary" yaml:"ordinary" mapstructure:"ordinary"`

	// PctS corresponds to the JSON schema field "pct%s".
	PctS string `json:"pct%s" yaml:"pct%s" mapstructure:"pct%s"`

	// Punct corresponds to the JSON schema field "punct!#$&()*+-./:;<=>?@[]^_{|}~".
	Punct string `json:"punct!#$&()*+-./:;<=>?@[]^_{|}~" yaml:"punct!#$&()*+-./:;<=>?@[]^_{|}~" mapstructure:"punct!#$&()*+-./:;<=>?@[]^_{|}~"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *PropertyNameEscaping) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return fmt.Errorf("unmarshal raw PropertyNameEscaping: %w", err)
	}
	if _, ok := raw["arrPct%s"]; raw != nil && !ok {
		return fmt.Errorf("field arrPct%%s in PropertyNameEscaping: required")
	}
	if _, ok := raw["ordinary"]; raw != nil && !ok {
		return fmt.Errorf("field ordinary in PropertyNameEscaping: required")
	}
	if _, ok := raw["pct%s"]; raw != nil && !ok {
		return fmt.Errorf("field pct%%s in PropertyNameEscaping: required")
	}
	if _, ok := raw["punct!#$&()*+-./:;<=>?@[]^_{|}~"]; raw != nil && !ok {
		return fmt.Errorf("field punct!#$&()*+-./:;<=>?@[]^_{|}~ in PropertyNameEscaping: required")
	}
	type Plain PropertyNameEscaping
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return fmt.Errorf("unmarshal PropertyNameEscaping: %w", err)
	}
	if plain.ArrPctS != nil && len(plain.ArrPctS) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "arrPct%s", 1)
	}
	for i1 := range plain.ArrPctS {
		if plain.ArrPctS[i1] != nil && len(plain.ArrPctS[i1]) < 1 {
			return fmt.Errorf("field %s length: must be >= %d", fmt.Sprintf("%s[%d]", "arrPct%s", i1), 1)
		}
	}
	*j = PropertyNameEscaping(plain)
	return nil
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *PropertyNameEscaping) UnmarshalYAML(value *yaml.Node) error {
	var raw map[string]interface{}
	if err := value.Decode(&raw); err != nil {
		return fmt.Errorf("unmarshal raw PropertyNameEscaping: %w", err)
	}
	if _, ok := raw["arrPct%s"]; raw != nil && !ok {
		return fmt.Errorf("field arrPct%%s in PropertyNameEscaping: required")
	}
	if _, ok := raw["ordinary"]; raw != nil && !ok {
		return fmt.Errorf("field ordinary in PropertyNameEscaping: required")
	}
	if _, ok := raw["pct%s"]; raw != nil && !ok {
		return fmt.Errorf("field pct%%s in PropertyNameEscaping: required")
	}
	if _, ok := raw["punct!#$&()*+-./:;<=>?@[]^_{|}~"]; raw != nil && !ok {
		return fmt.Errorf("field punct!#$&()*+-./:;<=>?@[]^_{|}~ in PropertyNameEscaping: required")
	}
	type Plain PropertyNameEscaping
	var plain Plain
	if err := value.Decode(&plain); err != nil {
		return fmt.Errorf("unmarshal PropertyNameEscaping: %w", err)
	}
	if plain.ArrPctS != nil && len(plain.ArrPctS) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "arrPct%s", 1)
	}
	for i1 := range plain.ArrPctS {
		if plain.ArrPctS[i1] != nil && len(plain.ArrPctS[i1]) < 1 {
			return fmt.Errorf("field %s length: must be >= %d", fmt.Sprintf("%s[%d]", "arrPct%s", i1), 1)
		}
	}
	*j = PropertyNameEscaping(plain)
	return nil
}
