// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package test

import "encoding/json"
import "fmt"
import "github.com/go-viper/mapstructure/v2"
import yaml "gopkg.in/yaml.v3"
import "reflect"
import "strings"

// Generated with Tags set to json only, so no field carries a yaml tag. yaml.v3
// binds such a field under its lowercased Go name, and pruning
// AdditionalProperties must remove that same key.
type YamlUntaggedFields struct {
	// Bound by yaml.v3 as `foo`, the lowercased name of the field Foo.
	Foo *string `json:"foo,omitempty,omitzero"`

	AdditionalProperties map[string]string `mapstructure:",remain"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *YamlUntaggedFields) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return fmt.Errorf("unmarshal raw YamlUntaggedFields: %w", err)
	}
	type Plain YamlUntaggedFields
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if v, ok := raw[""]; !ok || v == nil {
		plain.AdditionalProperties = map[string]string{}
	}
	st := reflect.TypeOf(Plain{})
	for i := 0; i < st.NumField(); i++ {
		f := st.Field(i)
		if f.Name == "AdditionalProperties" {
			continue
		}
		name := strings.Split(f.Tag.Get("json"), ",")[0]
		if name == "-" {
			continue
		}
		if name == "" {
			name = f.Name
		}
		for k := range raw {
			if strings.EqualFold(k, name) {
				delete(raw, k)
			}
		}
	}
	if err := mapstructure.Decode(raw, &plain.AdditionalProperties); err != nil {
		return err
	}
	*j = YamlUntaggedFields(plain)
	return nil
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *YamlUntaggedFields) UnmarshalYAML(value *yaml.Node) error {
	var raw map[string]interface{}
	if err := value.Decode(&raw); err != nil {
		return fmt.Errorf("unmarshal raw YamlUntaggedFields: %w", err)
	}
	type Plain YamlUntaggedFields
	var plain Plain
	if err := value.Decode(&plain); err != nil {
		return err
	}
	if v, ok := raw[""]; !ok || v == nil {
		plain.AdditionalProperties = map[string]string{}
	}
	st := reflect.TypeOf(Plain{})
	for i := 0; i < st.NumField(); i++ {
		f := st.Field(i)
		if f.Name == "AdditionalProperties" {
			continue
		}
		name := strings.Split(f.Tag.Get("yaml"), ",")[0]
		if name == "-" {
			continue
		}
		if name == "" {
			name = strings.ToLower(f.Name)
		}
		for k := range raw {
			if k == name {
				delete(raw, k)
			}
		}
	}
	if err := mapstructure.Decode(raw, &plain.AdditionalProperties); err != nil {
		return err
	}
	*j = YamlUntaggedFields(plain)
	return nil
}
