// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package test

import "encoding/json"
import "fmt"
import yaml "gopkg.in/yaml.v3"
import "reflect"

type EnumIfWithExtraRequiredOnIf struct {
	// Details corresponds to the JSON schema field "details".
	Details *string `json:"details,omitempty,omitzero" yaml:"details,omitempty" mapstructure:"details,omitempty"`

	// Kind corresponds to the JSON schema field "kind".
	Kind EnumIfWithExtraRequiredOnIfKind `json:"kind" yaml:"kind" mapstructure:"kind"`
}

type EnumIfWithExtraRequiredOnIfKind string

const EnumIfWithExtraRequiredOnIfKindA EnumIfWithExtraRequiredOnIfKind = "a"
const EnumIfWithExtraRequiredOnIfKindB EnumIfWithExtraRequiredOnIfKind = "b"

var enumValues_EnumIfWithExtraRequiredOnIfKind = []interface{}{
	"a",
	"b",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *EnumIfWithExtraRequiredOnIfKind) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_EnumIfWithExtraRequiredOnIfKind {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_EnumIfWithExtraRequiredOnIfKind, v)
	}
	*j = EnumIfWithExtraRequiredOnIfKind(v)
	return nil
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *EnumIfWithExtraRequiredOnIfKind) UnmarshalYAML(value *yaml.Node) error {
	var v string
	if err := value.Decode(&v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_EnumIfWithExtraRequiredOnIfKind {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_EnumIfWithExtraRequiredOnIfKind, v)
	}
	*j = EnumIfWithExtraRequiredOnIfKind(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *EnumIfWithExtraRequiredOnIf) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return fmt.Errorf("unmarshal raw EnumIfWithExtraRequiredOnIf: %w", err)
	}
	if _, ok := raw["kind"]; raw != nil && !ok {
		return fmt.Errorf("field kind in EnumIfWithExtraRequiredOnIf: required")
	}
	type Plain EnumIfWithExtraRequiredOnIf
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return fmt.Errorf("unmarshal EnumIfWithExtraRequiredOnIf: %w", err)
	}
	*j = EnumIfWithExtraRequiredOnIf(plain)
	return nil
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *EnumIfWithExtraRequiredOnIf) UnmarshalYAML(value *yaml.Node) error {
	var raw map[string]interface{}
	if err := value.Decode(&raw); err != nil {
		return fmt.Errorf("unmarshal raw EnumIfWithExtraRequiredOnIf: %w", err)
	}
	if _, ok := raw["kind"]; raw != nil && !ok {
		return fmt.Errorf("field kind in EnumIfWithExtraRequiredOnIf: required")
	}
	type Plain EnumIfWithExtraRequiredOnIf
	var plain Plain
	if err := value.Decode(&plain); err != nil {
		return fmt.Errorf("unmarshal EnumIfWithExtraRequiredOnIf: %w", err)
	}
	*j = EnumIfWithExtraRequiredOnIf(plain)
	return nil
}
