// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package test

import "encoding/json"
import "fmt"
import "github.com/go-viper/mapstructure/v2"
import yaml "gopkg.in/yaml.v3"
import "reflect"
import "strings"

type ObjectWithPropsAdditionalProperties struct {
	// Bar corresponds to the JSON schema field "bar".
	Bar *string `json:"bar,omitempty,omitzero" yaml:"bar,omitempty" mapstructure:"bar,omitempty"`

	// Foo corresponds to the JSON schema field "foo".
	Foo *string `json:"foo,omitempty,omitzero" yaml:"foo,omitempty" mapstructure:"foo,omitempty"`

	AdditionalProperties map[string]interface{} `mapstructure:",remain"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ObjectWithPropsAdditionalProperties) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return fmt.Errorf("unmarshal raw ObjectWithPropsAdditionalProperties: %w", err)
	}
	type Plain ObjectWithPropsAdditionalProperties
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return fmt.Errorf("unmarshal ObjectWithPropsAdditionalProperties: %w", err)
	}
	if v, ok := raw[""]; !ok || v == nil {
		plain.AdditionalProperties = map[string]interface{}{}
	}
	st := reflect.TypeOf(Plain{})
	for i := 0; i < st.NumField(); i++ {
		f := st.Field(i)
		if f.Name == "AdditionalProperties" {
			continue
		}
		name := strings.Split(f.Tag.Get("json"), ",")[0]
		if name == "-" {
			continue
		}
		if name == "" {
			name = f.Name
		}
		for k := range raw {
			if strings.EqualFold(k, name) {
				delete(raw, k)
			}
		}
	}
	if err := mapstructure.Decode(raw, &plain.AdditionalProperties); err != nil {
		return fmt.Errorf("decode additional properties for ObjectWithPropsAdditionalProperties: %w", err)
	}
	*j = ObjectWithPropsAdditionalProperties(plain)
	return nil
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *ObjectWithPropsAdditionalProperties) UnmarshalYAML(value *yaml.Node) error {
	var raw map[string]interface{}
	if err := value.Decode(&raw); err != nil {
		return fmt.Errorf("unmarshal raw ObjectWithPropsAdditionalProperties: %w", err)
	}
	type Plain ObjectWithPropsAdditionalProperties
	var plain Plain
	if err := value.Decode(&plain); err != nil {
		return fmt.Errorf("unmarshal ObjectWithPropsAdditionalProperties: %w", err)
	}
	if v, ok := raw[""]; !ok || v == nil {
		plain.AdditionalProperties = map[string]interface{}{}
	}
	st := reflect.TypeOf(Plain{})
	for i := 0; i < st.NumField(); i++ {
		f := st.Field(i)
		if f.Name == "AdditionalProperties" {
			continue
		}
		name := strings.Split(f.Tag.Get("yaml"), ",")[0]
		if name == "-" {
			continue
		}
		if name == "" {
			name = f.Name
		}
		for k := range raw {
			if strings.EqualFold(k, name) {
				delete(raw, k)
			}
		}
	}
	if err := mapstructure.Decode(raw, &plain.AdditionalProperties); err != nil {
		return fmt.Errorf("decode additional properties for ObjectWithPropsAdditionalProperties: %w", err)
	}
	*j = ObjectWithPropsAdditionalProperties(plain)
	return nil
}
