// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package test

type TupleItemsOpen struct {
	// additionalItems is a real `not` constraint, not the false schema: anything
	// non-integer may follow position 0. Must NOT collapse to []string.
	NotAdditional []interface{} `json:"notAdditional,omitempty,omitzero" yaml:"notAdditional,omitempty" mapstructure:"notAdditional,omitempty"`

	// additionalItems permits further strings, so the array is still open.
	TypedAdditional []interface{} `json:"typedAdditional,omitempty,omitzero" yaml:"typedAdditional,omitempty" mapstructure:"typedAdditional,omitempty"`

	// A one-element tuple with no additionalItems:false and no maxItems. Position 0
	// must be a string, but positions 1+ are unconstrained, so this must NOT collapse
	// to []string.
	Unrestricted []interface{} `json:"unrestricted,omitempty,omitzero" yaml:"unrestricted,omitempty" mapstructure:"unrestricted,omitempty"`
}
