// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package test

import "encoding/json"
import "fmt"
import yaml "gopkg.in/yaml.v3"

// A try-each variant refers back to the oneOf that holds it. The holder is
// registered before its variants, so Children resolves to it; before, Children got
// a type that was never declared.
type Node struct {
	Variant0 *NodeVariant0 `json:"-" yaml:"-"`

	Variant1 *NodeVariant1 `json:"-" yaml:"-"`
}

type NodeVariant0 struct {
	// Leaf corresponds to the JSON schema field "leaf".
	Leaf string `json:"leaf" yaml:"leaf" mapstructure:"leaf"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *NodeVariant0) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return fmt.Errorf("unmarshal raw NodeVariant0: %w", err)
	}
	if _, ok := raw["leaf"]; raw != nil && !ok {
		return fmt.Errorf("field leaf in NodeVariant0: required")
	}
	type Plain NodeVariant0
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return fmt.Errorf("unmarshal NodeVariant0: %w", err)
	}
	*j = NodeVariant0(plain)
	return nil
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *NodeVariant0) UnmarshalYAML(value *yaml.Node) error {
	var raw map[string]interface{}
	if err := value.Decode(&raw); err != nil {
		return fmt.Errorf("unmarshal raw NodeVariant0: %w", err)
	}
	if _, ok := raw["leaf"]; raw != nil && !ok {
		return fmt.Errorf("field leaf in NodeVariant0: required")
	}
	type Plain NodeVariant0
	var plain Plain
	if err := value.Decode(&plain); err != nil {
		return fmt.Errorf("unmarshal NodeVariant0: %w", err)
	}
	*j = NodeVariant0(plain)
	return nil
}

type NodeVariant1 struct {
	// Children corresponds to the JSON schema field "children".
	Children []Node `json:"children" yaml:"children" mapstructure:"children"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *NodeVariant1) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return fmt.Errorf("unmarshal raw NodeVariant1: %w", err)
	}
	if _, ok := raw["children"]; raw != nil && !ok {
		return fmt.Errorf("field children in NodeVariant1: required")
	}
	type Plain NodeVariant1
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return fmt.Errorf("unmarshal NodeVariant1: %w", err)
	}
	*j = NodeVariant1(plain)
	return nil
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *NodeVariant1) UnmarshalYAML(value *yaml.Node) error {
	var raw map[string]interface{}
	if err := value.Decode(&raw); err != nil {
		return fmt.Errorf("unmarshal raw NodeVariant1: %w", err)
	}
	if _, ok := raw["children"]; raw != nil && !ok {
		return fmt.Errorf("field children in NodeVariant1: required")
	}
	type Plain NodeVariant1
	var plain Plain
	if err := value.Decode(&plain); err != nil {
		return fmt.Errorf("unmarshal NodeVariant1: %w", err)
	}
	*j = NodeVariant1(plain)
	return nil
}

// MarshalJSON implements json.Marshaler. Exactly one variant
// pointer must be non-nil; otherwise marshaling errors.
func (j Node) MarshalJSON() ([]byte, error) {
	set := 0
	if j.Variant0 != nil {
		set++
	}
	if j.Variant1 != nil {
		set++
	}
	if set != 1 {
		return nil, fmt.Errorf("Node: exactly one variant must be set, got %d", set)
	}
	if j.Variant0 != nil {
		return json.Marshal(j.Variant0)
	}
	if j.Variant1 != nil {
		return json.Marshal(j.Variant1)
	}
	return nil, nil // unreachable
}

// MarshalYAML mirrors MarshalJSON.
func (j Node) MarshalYAML() (interface{}, error) {
	set := 0
	if j.Variant0 != nil {
		set++
	}
	if j.Variant1 != nil {
		set++
	}
	if set != 1 {
		return nil, fmt.Errorf("Node: exactly one variant must be set, got %d", set)
	}
	if j.Variant0 != nil {
		return j.Variant0, nil
	}
	if j.Variant1 != nil {
		return j.Variant1, nil
	}
	return nil, nil // unreachable
}

// UnmarshalJSON implements json.Unmarshaler. With no natural
// discriminator we try each variant in turn after a per-variant shape check;
// success requires exactly one variant to unmarshal without error.
func (j *Node) UnmarshalJSON(value []byte) error {
	// Reset to zero value so reusing the same holder across multiple
	// Unmarshal calls doesn't leave a previous winner set alongside the
	// new one (which would violate the one-variant-set invariant and
	// break the corresponding Marshal).
	*j = Node{}
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return fmt.Errorf("unmarshal Node: %w", err)
	}
	matched := 0
	var lastErr error

	// Variant 0: NodeVariant0
	{
		shapeOK := true
		if _, ok := raw["leaf"]; !ok {
			shapeOK = false
		}
		for k := range raw {
			switch k {
			case "leaf":
			default:
				shapeOK = false
			}
		}
		if shapeOK {
			var v NodeVariant0
			if err := json.Unmarshal(value, &v); err == nil {
				j.Variant0 = &v
				matched++
			} else {
				lastErr = err
			}
		}
	}

	// Variant 1: NodeVariant1
	{
		shapeOK := true
		if _, ok := raw["children"]; !ok {
			shapeOK = false
		}
		for k := range raw {
			switch k {
			case "children":
			default:
				shapeOK = false
			}
		}
		if shapeOK {
			var v NodeVariant1
			if err := json.Unmarshal(value, &v); err == nil {
				j.Variant1 = &v
				matched++
			} else {
				lastErr = err
			}
		}
	}

	if matched == 0 {
		if lastErr != nil {
			return fmt.Errorf("Node: no oneOf variant matched: %w", lastErr)
		}
		return fmt.Errorf("Node: no oneOf variant matched")
	}
	if matched > 1 {
		j.Variant0 = nil
		j.Variant1 = nil
		return fmt.Errorf("Node: ambiguous input — %d oneOf variants matched", matched)
	}
	return nil
}

// UnmarshalYAML mirrors UnmarshalJSON: try each variant after a
// shape check; exactly one must unmarshal without error.
func (j *Node) UnmarshalYAML(value *yaml.Node) error {
	// Reset to zero value so reusing the same holder across multiple
	// Unmarshal calls doesn't leave a previous winner set alongside the
	// new one (which would violate the one-variant-set invariant and
	// break the corresponding Marshal).
	*j = Node{}
	var raw map[string]interface{}
	if err := value.Decode(&raw); err != nil {
		return fmt.Errorf("unmarshal Node: %w", err)
	}
	matched := 0
	var lastErr error

	// Variant 0: NodeVariant0
	{
		shapeOK := true
		if _, ok := raw["leaf"]; !ok {
			shapeOK = false
		}
		for k := range raw {
			switch k {
			case "leaf":
			default:
				shapeOK = false
			}
		}
		if shapeOK {
			var v NodeVariant0
			if err := value.Decode(&v); err == nil {
				j.Variant0 = &v
				matched++
			} else {
				lastErr = err
			}
		}
	}

	// Variant 1: NodeVariant1
	{
		shapeOK := true
		if _, ok := raw["children"]; !ok {
			shapeOK = false
		}
		for k := range raw {
			switch k {
			case "children":
			default:
				shapeOK = false
			}
		}
		if shapeOK {
			var v NodeVariant1
			if err := value.Decode(&v); err == nil {
				j.Variant1 = &v
				matched++
			} else {
				lastErr = err
			}
		}
	}

	if matched == 0 {
		if lastErr != nil {
			return fmt.Errorf("Node: no oneOf variant matched: %w", lastErr)
		}
		return fmt.Errorf("Node: no oneOf variant matched")
	}
	if matched > 1 {
		j.Variant0 = nil
		j.Variant1 = nil
		return fmt.Errorf("Node: ambiguous input — %d oneOf variants matched", matched)
	}
	return nil
}
