// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package test

import "encoding/json"
import "fmt"
import yaml "gopkg.in/yaml.v3"
import "reflect"

type WithElse struct {
	// Category corresponds to the JSON schema field "category".
	Category WithElseCategory `json:"category" yaml:"category" mapstructure:"category"`

	// Label corresponds to the JSON schema field "label".
	Label *string `json:"label,omitempty,omitzero" yaml:"label,omitempty" mapstructure:"label,omitempty"`

	// Weight corresponds to the JSON schema field "weight".
	Weight *int `json:"weight,omitempty,omitzero" yaml:"weight,omitempty" mapstructure:"weight,omitempty"`
}

type WithElseCategory string

const WithElseCategoryPrimary WithElseCategory = "primary"
const WithElseCategorySecondary WithElseCategory = "secondary"

var enumValues_WithElseCategory = []interface{}{
	"primary",
	"secondary",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *WithElseCategory) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_WithElseCategory {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_WithElseCategory, v)
	}
	*j = WithElseCategory(v)
	return nil
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *WithElseCategory) UnmarshalYAML(value *yaml.Node) error {
	var v string
	if err := value.Decode(&v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_WithElseCategory {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_WithElseCategory, v)
	}
	*j = WithElseCategory(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *WithElse) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return fmt.Errorf("unmarshal raw WithElse: %w", err)
	}
	if _, ok := raw["category"]; raw != nil && !ok {
		return fmt.Errorf("field category in WithElse: required")
	}
	rawDisc, hasDisc := raw["category"]
	if hasDisc {
		discStr, isStr := rawDisc.(string)
		if !isStr {
			return fmt.Errorf("field category in WithElse: must be a string for discriminator dispatch")
		}
		if discStr == "primary" {
			if _, ok := raw["weight"]; !ok {
				return fmt.Errorf("field weight in WithElse (when category='primary'): required")
			}
		} else {
			if _, ok := raw["label"]; !ok {
				return fmt.Errorf("field label in WithElse (when category!='primary'): required")
			}
		}
	}
	type Plain WithElse
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return fmt.Errorf("unmarshal WithElse: %w", err)
	}
	*j = WithElse(plain)
	return nil
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *WithElse) UnmarshalYAML(value *yaml.Node) error {
	var raw map[string]interface{}
	if err := value.Decode(&raw); err != nil {
		return fmt.Errorf("unmarshal raw WithElse: %w", err)
	}
	if _, ok := raw["category"]; raw != nil && !ok {
		return fmt.Errorf("field category in WithElse: required")
	}
	rawDisc, hasDisc := raw["category"]
	if hasDisc {
		discStr, isStr := rawDisc.(string)
		if !isStr {
			return fmt.Errorf("field category in WithElse: must be a string for discriminator dispatch")
		}
		if discStr == "primary" {
			if _, ok := raw["weight"]; !ok {
				return fmt.Errorf("field weight in WithElse (when category='primary'): required")
			}
		} else {
			if _, ok := raw["label"]; !ok {
				return fmt.Errorf("field label in WithElse (when category!='primary'): required")
			}
		}
	}
	type Plain WithElse
	var plain Plain
	if err := value.Decode(&plain); err != nil {
		return fmt.Errorf("unmarshal WithElse: %w", err)
	}
	*j = WithElse(plain)
	return nil
}
