// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package test

import "encoding/json"
import "time"

type Duration struct {
	// MyObject corresponds to the JSON schema field "myObject".
	MyObject *DurationMyObject `json:"myObject,omitempty" yaml:"myObject,omitempty" mapstructure:"myObject,omitempty"`
}

type DurationMyObject struct {
	// MyDateTime corresponds to the JSON schema field "myDateTime".
	MyDateTime *time.Duration `json:"myDateTime,omitempty" yaml:"myDateTime,omitempty" mapstructure:"myDateTime,omitempty"`
}
