// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package test

import "time"

// example of a reference to a date-time formatted string
type DatetimeRef struct {
	// Time corresponds to the JSON schema field "time".
	Time Timedef `json:"time,omitempty" yaml:"time,omitempty" mapstructure:"time,omitempty"`
}

type Timedef *time.Time
