---
name: development
on:
  push:
    branches:
      - main
  pull_request:
permissions:
  contents: read
  pull-requests: read
concurrency:
  group: ${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}
  cancel-in-progress: true
jobs:
  qa:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
        with:
          fetch-depth: 1
      - name: Setup Golang
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7
        with:
          go-version: 1.25.10
      - name: Setup workspace
        run: cp go.work.dist go.work
      - name: Download golangci-lint installer
        run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/v2.12.2/install.sh -o /tmp/install-golangci-lint.sh
      - name: Install golangci-lint
        run: sh /tmp/install-golangci-lint.sh -b /usr/local/bin v2.12.2
      - name: Lint Go files
        run: ./scripts/lint-golang.sh
      - name: Run tests
        run: ./scripts/test.sh
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v6
      - name: Create dedicated docker buildx builder instance
        run: docker buildx create --driver=docker-container --name container --use
      - name: Build binaries
        uses: goreleaser/goreleaser-action@f06c13b6b1a9625abc9e6e439d9c05a8f2190e94 # v7
        with:
          distribution: goreleaser
          version: 2.15.4
          args: release --verbose --snapshot --clean
        env:
          GO_VERSION: 1.25.10
