---
name: development
on:
  push:
    branches:
      - main
  pull_request:
permissions:
  contents: read
  pull-requests: read
concurrency:
  group: ${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}
  cancel-in-progress: true
jobs:
  qa:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 1
      - name: Setup Golang
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6
        with:
          go-version: 1.25.10
      - name: Setup workspace
        run: cp go.work.dist go.work
      - name: Download golangci-lint installer
        run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/v2.12.2/install.sh -o /tmp/install-golangci-lint.sh
      - name: Install golangci-lint
        run: sh /tmp/install-golangci-lint.sh -b /usr/local/bin v2.12.2
      - name: Lint Go files
        run: ./scripts/lint-golang.sh
      - name: Run tests
        run: ./scripts/test.sh
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@57e3a136b779b570ffcdbf80b3bdc90e7fab3de2 # v6
      - name: Create dedicated docker buildx builder instance
        run: docker buildx create --driver=docker-container --name container
      - name: Build binaries
        uses: goreleaser/goreleaser-action@1a80836c5c9d9e5755a25cb59ec6f45a3b5f41a8 # v7
        with:
          distribution: goreleaser
          version: 2.15.4
          args: release --verbose --snapshot --clean
        env:
          GO_VERSION: 1.25.10
