---
name: prerelease
on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+-rc.[0-9]+
      - v[0-9]+.[0-9]+.[0-9]+-beta.[0-9]+
      - v[0-9]+.[0-9]+.[0-9]+-alpha.[0-9]+
permissions:
  contents: write
concurrency:
  group: ${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}
  cancel-in-progress: true
jobs:
  prerelease:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 1
      - name: Fetch all tags
        run: git fetch --force --tags
      - name: Setup Golang
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6
        with:
          go-version: 1.25.10
      - name: Setup workspace
        run: cp go.work.dist go.work
      - name: Create dedicated docker buildx builder instance
        run: docker buildx create --driver=docker-container --name container --use
      - name: Run GoReleaser for release
        uses: goreleaser/goreleaser-action@1a80836c5c9d9e5755a25cb59ec6f45a3b5f41a8 # v7
        with:
          distribution: goreleaser
          version: 2.15.4
          args: release --verbose --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          GO_VERSION: 1.25.10
