---
name: prerelease
on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+-rc.[0-9]+
      - v[0-9]+.[0-9]+.[0-9]+-beta.[0-9]+
      - v[0-9]+.[0-9]+.[0-9]+-alpha.[0-9]+
permissions:
  contents: write
concurrency:
  group: ${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}
  cancel-in-progress: true
jobs:
  prerelease:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
        with:
          fetch-depth: 1
      - name: Fetch all tags
        run: git fetch --force --tags
      - name: Setup Golang
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7
        with:
          go-version: 1.25.10
      - name: Setup workspace
        run: cp go.work.dist go.work
      - name: Create dedicated docker buildx builder instance
        run: docker buildx create --driver=docker-container --name container --use
      - name: Run GoReleaser for release
        uses: goreleaser/goreleaser-action@f06c13b6b1a9625abc9e6e439d9c05a8f2190e94 # v7
        with:
          distribution: goreleaser
          version: 2.15.4
          args: release --verbose --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          GO_VERSION: 1.25.10
