// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package test

import "encoding/json"
import "fmt"
import yaml "gopkg.in/yaml.v3"

type OmitNone struct {
	// MyArray corresponds to the JSON schema field "myArray".
	MyArray []interface{} `json:"myArray"`

	// MyBoolean corresponds to the JSON schema field "myBoolean".
	MyBoolean *bool `json:"myBoolean"`

	// MyInteger corresponds to the JSON schema field "myInteger".
	MyInteger *int `json:"myInteger"`

	// MyMap corresponds to the JSON schema field "myMap".
	MyMap OmitNoneMyMap `json:"myMap"`

	// MyNull corresponds to the JSON schema field "myNull".
	MyNull interface{} `json:"myNull"`

	// MyNullArray corresponds to the JSON schema field "myNullArray".
	MyNullArray []interface{} `json:"myNullArray"`

	// MyNumber corresponds to the JSON schema field "myNumber".
	MyNumber *float64 `json:"myNumber"`

	// MyObjectArray corresponds to the JSON schema field "myObjectArray".
	MyObjectArray []OmitNoneMyObjectArrayElem `json:"myObjectArray"`

	// MyString corresponds to the JSON schema field "myString".
	MyString *string `json:"myString"`

	// MyStringArray corresponds to the JSON schema field "myStringArray".
	MyStringArray []string `json:"myStringArray"`
}

type OmitNoneMyMap map[string]float64

type OmitNoneMyObjectArrayElem map[string]interface{}

// UnmarshalJSON implements json.Unmarshaler.
func (j *OmitNone) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	type Plain OmitNone
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if plain.MyNull != nil {
		return fmt.Errorf("field %s: must be null", "myNull")
	}
	for i0 := range plain.MyNullArray {
		if plain.MyNullArray[i0] != nil {
			return fmt.Errorf("field %s: must be null", fmt.Sprintf("myNullArray[%d]", i0))
		}
	}
	*j = OmitNone(plain)
	return nil
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *OmitNone) UnmarshalYAML(value *yaml.Node) error {
	var raw map[string]interface{}
	if err := value.Decode(&raw); err != nil {
		return err
	}
	type Plain OmitNone
	var plain Plain
	if err := value.Decode(&plain); err != nil {
		return err
	}
	if plain.MyNull != nil {
		return fmt.Errorf("field %s: must be null", "myNull")
	}
	for i0 := range plain.MyNullArray {
		if plain.MyNullArray[i0] != nil {
			return fmt.Errorf("field %s: must be null", fmt.Sprintf("myNullArray[%d]", i0))
		}
	}
	*j = OmitNone(plain)
	return nil
}
