// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package test

import "bytes"
import "encoding/json"
import "fmt"
import yaml "gopkg.in/yaml.v3"
import "time"

type OneOfConstrainedVariant struct {
	// A variant carrying a constraint the wrapper has nowhere to enforce disqualifies
	// the primitive wrapper, because the wrapper dispatches on JSON token kind alone.
	// Degrades to interface{} — and must say so.
	StillRejected interface{} `json:"stillRejected,omitempty,omitzero" yaml:"stillRejected,omitempty" mapstructure:"stillRejected,omitempty"`

	// A temporal `format` is a type mapping, not a constraint: the string branch
	// decodes into time.Time exactly as the non-oneOf path does. It compiles to a
	// wrapper and must NOT warn.
	TimeOrNumber *OneOfConstrainedVariantTimeOrNumber `json:"timeOrNumber,omitempty,omitzero" yaml:"timeOrNumber,omitempty" mapstructure:"timeOrNumber,omitempty"`

	// The same shape without constraints compiles to a typed wrapper, and must NOT
	// warn.
	Unconstrained *OneOfConstrainedVariantUnconstrained `json:"unconstrained,omitempty,omitzero" yaml:"unconstrained,omitempty" mapstructure:"unconstrained,omitempty"`
}

// A temporal `format` is a type mapping, not a constraint: the string branch
// decodes into time.Time exactly as the non-oneOf path does. It compiles to a
// wrapper and must NOT warn.
type OneOfConstrainedVariantTimeOrNumber struct {
	value interface{}

	present bool
}

// AsDateTime returns the value as a time.Time and reports whether it was a
// date-time.
func (j *OneOfConstrainedVariantTimeOrNumber) AsDateTime() (time.Time, bool) {
	if j == nil || !j.present {
		return time.Time{}, false
	}
	v, ok := j.value.(time.Time)
	return v, ok
}

// AsNumber returns the value as a float64 and reports whether it was numeric.
func (j *OneOfConstrainedVariantTimeOrNumber) AsNumber() (float64, bool) {
	if j == nil || !j.present {
		return 0, false
	}
	v, ok := j.value.(float64)
	return v, ok
}

// IsZero reports whether the wrapper has not been populated by
// Unmarshal{JSON,YAML}; supports the encoding/json `omitzero` tag.
func (j *OneOfConstrainedVariantTimeOrNumber) IsZero() bool {
	return j == nil || !j.present
}

// MarshalJSON implements json.Marshaler.
func (j *OneOfConstrainedVariantTimeOrNumber) MarshalJSON() ([]byte, error) {
	if j == nil || !j.present {
		return nil, fmt.Errorf("OneOfConstrainedVariantTimeOrNumber: cannot marshal unset value (schema does not allow null)")
	}
	if j.value == nil {
		return nil, fmt.Errorf("OneOfConstrainedVariantTimeOrNumber: cannot marshal nil value (schema does not allow null)")
	}
	return json.Marshal(j.value)
}

// MarshalYAML implements yaml.Marshaler.
func (j *OneOfConstrainedVariantTimeOrNumber) MarshalYAML() (interface{}, error) {
	if j == nil || !j.present {
		return nil, fmt.Errorf("OneOfConstrainedVariantTimeOrNumber: cannot marshal unset value (schema does not allow null)")
	}
	if j.value == nil {
		return nil, fmt.Errorf("OneOfConstrainedVariantTimeOrNumber: cannot marshal nil value (schema does not allow null)")
	}
	return j.value, nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *OneOfConstrainedVariantTimeOrNumber) UnmarshalJSON(value []byte) error {
	dec := json.NewDecoder(bytes.NewReader(value))
	dec.UseNumber()
	tok, err := dec.Token()
	if err != nil {
		return err
	}
	switch tok.(type) {
	case string:
		var v time.Time
		if err := json.Unmarshal(value, &v); err != nil {
			return err
		}
		j.value = v
	case json.Number:
		var v float64
		if err := json.Unmarshal(value, &v); err != nil {
			return err
		}
		j.value = v
	default:
		return fmt.Errorf("OneOfConstrainedVariantTimeOrNumber: unsupported JSON value of type %T", tok)
	}
	j.present = true
	return nil
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *OneOfConstrainedVariantTimeOrNumber) UnmarshalYAML(value *yaml.Node) error {
	if value.Kind != yaml.ScalarNode {
		return fmt.Errorf("OneOfConstrainedVariantTimeOrNumber: expected scalar YAML node")
	}
	switch value.Tag {
	case "!!str":
		var v time.Time
		if err := value.Decode(&v); err != nil {
			return err
		}
		j.value = v
	case "!!int", "!!float":
		var v float64
		if err := value.Decode(&v); err != nil {
			return err
		}
		j.value = v
	default:
		return fmt.Errorf("OneOfConstrainedVariantTimeOrNumber: unsupported YAML scalar tag %q", value.Tag)
	}
	j.present = true
	return nil
}

// Value returns the decoded primitive payload.
func (j *OneOfConstrainedVariantTimeOrNumber) Value() any {
	if j == nil {
		return nil
	}
	return j.value
}

// The same shape without constraints compiles to a typed wrapper, and must NOT
// warn.
type OneOfConstrainedVariantUnconstrained struct {
	value interface{}

	present bool
}

// AsBool returns the value as a bool and reports whether it was a bool.
func (j *OneOfConstrainedVariantUnconstrained) AsBool() (bool, bool) {
	if j == nil || !j.present {
		return false, false
	}
	v, ok := j.value.(bool)
	return v, ok
}

// AsNumber returns the value as a float64 and reports whether it was numeric.
func (j *OneOfConstrainedVariantUnconstrained) AsNumber() (float64, bool) {
	if j == nil || !j.present {
		return 0, false
	}
	v, ok := j.value.(float64)
	return v, ok
}

// AsString returns the value as a string and reports whether it was a string.
func (j *OneOfConstrainedVariantUnconstrained) AsString() (string, bool) {
	if j == nil || !j.present {
		return "", false
	}
	v, ok := j.value.(string)
	return v, ok
}

// IsZero reports whether the wrapper has not been populated by
// Unmarshal{JSON,YAML}; supports the encoding/json `omitzero` tag.
func (j *OneOfConstrainedVariantUnconstrained) IsZero() bool {
	return j == nil || !j.present
}

// MarshalJSON implements json.Marshaler.
func (j *OneOfConstrainedVariantUnconstrained) MarshalJSON() ([]byte, error) {
	if j == nil || !j.present {
		return nil, fmt.Errorf("OneOfConstrainedVariantUnconstrained: cannot marshal unset value (schema does not allow null)")
	}
	if j.value == nil {
		return nil, fmt.Errorf("OneOfConstrainedVariantUnconstrained: cannot marshal nil value (schema does not allow null)")
	}
	return json.Marshal(j.value)
}

// MarshalYAML implements yaml.Marshaler.
func (j *OneOfConstrainedVariantUnconstrained) MarshalYAML() (interface{}, error) {
	if j == nil || !j.present {
		return nil, fmt.Errorf("OneOfConstrainedVariantUnconstrained: cannot marshal unset value (schema does not allow null)")
	}
	if j.value == nil {
		return nil, fmt.Errorf("OneOfConstrainedVariantUnconstrained: cannot marshal nil value (schema does not allow null)")
	}
	return j.value, nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *OneOfConstrainedVariantUnconstrained) UnmarshalJSON(value []byte) error {
	dec := json.NewDecoder(bytes.NewReader(value))
	dec.UseNumber()
	tok, err := dec.Token()
	if err != nil {
		return err
	}
	switch tok.(type) {
	case string:
		var v string
		if err := json.Unmarshal(value, &v); err != nil {
			return err
		}
		j.value = v
	case json.Number:
		var v float64
		if err := json.Unmarshal(value, &v); err != nil {
			return err
		}
		j.value = v
	case bool:
		var v bool
		if err := json.Unmarshal(value, &v); err != nil {
			return err
		}
		j.value = v
	default:
		return fmt.Errorf("OneOfConstrainedVariantUnconstrained: unsupported JSON value of type %T", tok)
	}
	j.present = true
	return nil
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *OneOfConstrainedVariantUnconstrained) UnmarshalYAML(value *yaml.Node) error {
	if value.Kind != yaml.ScalarNode {
		return fmt.Errorf("OneOfConstrainedVariantUnconstrained: expected scalar YAML node")
	}
	switch value.Tag {
	case "!!str":
		var v string
		if err := value.Decode(&v); err != nil {
			return err
		}
		j.value = v
	case "!!int", "!!float":
		var v float64
		if err := value.Decode(&v); err != nil {
			return err
		}
		j.value = v
	case "!!bool":
		var v bool
		if err := value.Decode(&v); err != nil {
			return err
		}
		j.value = v
	default:
		return fmt.Errorf("OneOfConstrainedVariantUnconstrained: unsupported YAML scalar tag %q", value.Tag)
	}
	j.present = true
	return nil
}

// Value returns the decoded primitive payload.
func (j *OneOfConstrainedVariantUnconstrained) Value() any {
	if j == nil {
		return nil
	}
	return j.value
}
